---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: varlogsn
  namespace: default
  labels:
    app.kubernetes.io/name: varlog
    app.kubernetes.io/component: varlogsn
    app.kubernetes.io/part-of: varlog
spec:
  template:
    spec:
      volumes:
        - name: varlogsn-data
          $patch: delete
        - name: varlogsn-data01
          hostPath:
            path: /data1/varlog/sn
            type: DirectoryOrCreate
        - name: varlogsn-data02
          hostPath:
            path: /data2/varlog/sn
            type: DirectoryOrCreate
        - name: varlogsn-data03
          hostPath:
            path: /data3/varlog/sn
            type: DirectoryOrCreate
        - name: varlogsn-data04
          hostPath:
            path: /data4/varlog/sn
            type: DirectoryOrCreate
      initContainers:
        - name: volume-perm
          command:
            - "sh"
            - "-c"
            - "chmod -R 777 /data1/varlog/sn && chmod -R 777 /data2/varlog/sn && chmod -R 777 /data3/varlog/sn && chmod -R 777 /data4/varlog/sn"
          volumeMounts:
            - name: varlogsn-data
              $patch: delete
            - name: varlogsn-data01
              mountPath: /data1/varlog/sn
            - name: varlogsn-data02
              mountPath: /data2/varlog/sn
            - name: varlogsn-data03
              mountPath: /data3/varlog/sn
            - name: varlogsn-data04
              mountPath: /data4/varlog/sn
      containers:
        - name: varlogsn
          command:
            - "python3"
          args:
            - "/varlog/bin/start_varlogsn.py"
            - "--cluster-id=$(CLUSTER_ID)"
            - "--listen=0.0.0.0:9091"
            - "--advertise=$(HOST_IP):9091"
            - "--admin=$(VARLOGADM_RPC_SERVICE_HOST):$(VARLOGADM_RPC_SERVICE_PORT)"
            - "--volumes=/data1/varlog/sn/data"
            - "--volumes=/data2/varlog/sn/data"
            - "--volumes=/data3/varlog/sn/data"
            - "--volumes=/data4/varlog/sn/data"
            - "--add-after-seconds=10"
            - "--retry-interval-seconds=10"
            - "--logtostderr"
            - "--log-dir=/data1/varlog/sn/logs"
          resources:
            limits:
              cpu: 16000m
              memory: 32Gi
            requests:
              cpu: 16000m
              memory: 32Gi
          volumeMounts:
            - name: varlogsn-data
              $patch: delete
            - name: varlogsn-data01
              mountPath: /data1/varlog/sn
            - name: varlogsn-data02
              mountPath: /data2/varlog/sn
            - name: varlogsn-data03
              mountPath: /data3/varlog/sn
            - name: varlogsn-data04
              mountPath: /data4/varlog/sn
