apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
spec:
  selector:
    app: jaeger
  ports:
  - name: collector
    port: 14250
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - name: collector
          containerPort: 14250
        - name: ui
          containerPort: 16686
        readinessProbe:
          tcpSocket:
            port: 14250
      dnsPolicy: ClusterFirst
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                  - "varlog-mr"
                  - "varlog-sn"
                  - "varlog-vms"
                  - "prometheus"
                - key: "component"
                  operator: NotIn
                  values:
                  - "otel-collector"
            topologyKey: "kubernetes.io/hostname"
