kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: varlog-mr
  namespace: default
  labels:
    app: varlog-mr
    name: varlog-mr
spec:
  selector:
    matchLabels:
      name: varlog-mr
  template:
    metadata:
      labels:
        app: varlog-mr
        name: varlog-mr
    spec:
      volumes:
      - name: varlog-mr-home
        hostPath:
          path: /varlog/mr
          type: DirectoryOrCreate
      initContainers:
      - name: volume-perm
        image: mdock.daumkakao.io/busybox:stable
        command:
        - "sh"
        - "-c"
        - "chmod -R 777 /varlog/mr"
        volumeMounts:
        - name: varlog-mr-home
          mountPath: /varlog/mr
      containers:
      - name: varlog-mr
        image: idock.daumkakao.io/varlog/varlog-mr:latest
        command:
        - "python3"
        - "/varlog/bin/vmr.py"
        ports:
        - name: rpc
          containerPort: 9092
        env:
        - name: TZ
          value: Asia/Seoul
        - name: VMS_ADDRESS
          value: "$(VARLOG_VMS_RPC_SERVICE_HOST):$(VARLOG_VMS_RPC_SERVICE_PORT)"
        - name: VMR_HOME
          value: /varlog/mr
        - name: COLLECTOR_NAME
          value: "otel"
        - name: COLLECTOR_ENDPOINT
          value: "localhost:4317"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            cpu: 3000m
            memory: 3Gi
          requests:
            cpu: 3000m
            memory: 3Gi
        volumeMounts:
        - name: varlog-mr-home
          mountPath: /varlog/mr
        readinessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "/varlog/tools/grpc_health_probe -addr=${HOST_IP}:9092"
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "/varlog/tools/grpc_health_probe -addr=${HOST_IP}:9092"
          periodSeconds: 10
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - varlog-mr
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: NotIn
                  values:
                  - "varlog-sn"
                  - "varlog-vms"
                  - "prometheus"
                  - "jaeger"
                - key: "component"
                  operator: NotIn
                  values:
                  - "otel-collector"
            topologyKey: "kubernetes.io/hostname"
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
