apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  labels:
    app: opentelemetry
    component: otel-agent-conf

data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: "otel-collector.default:4317"
        insecure: true

    processors:
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
      extensions: [health_check, pprof, zpages]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      initContainers:
      - name: "init-otel-collector"
        image: mdock.daumkakao.io/busybox:stable
        command:
        - "sh"
        - "-c"
        - "until nslookup otel-collector.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for otel-collector; sleep 2; done"
      containers:
      - command:
        - "/otelcol"
        - "--config=/conf/otel-agent-config.yaml"
        image: otel/opentelemetry-collector:latest
        name: otel-agent
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
      - name: otel-agent-config-vol
        configMap:
          name: otel-agent-conf
          items:
          - key: otel-agent-config
            path: otel-agent-config.yaml
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
