kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: varlog-sn
  namespace: default
  labels:
    app: varlog-sn
    name: varlog-sn
spec:
  selector:
    matchLabels:
      name: varlog-sn
  template:
    metadata:
      labels:
        app: varlog-sn
        name: varlog-sn
    spec:
      volumes:
      - name: varlog-sn-home
        hostPath:
          path: /varlog/data
          type: DirectoryOrCreate
      initContainers:
      - name: volume-perm
        image: mdock.daumkakao.io/busybox:stable
        command:
        - "sh"
        - "-c"
        - "chmod -R 777 /varlog/data"
        volumeMounts:
        - name: varlog-sn-home
          mountPath: /varlog/data
        imagePullPolicy: IfNotPresent
      containers:
      - name: varlog-sn
        image: idock.daumkakao.io/varlog/varlog-sn:latest
        command:
        - "python3"
        - "/varlog/bin/vsn.py"
        ports:
        - name: rpc
          containerPort: 9091
        env:
        - name: TZ
          value: Asia/Seoul
        - name: VMS_ADDRESS
          value: "$(VARLOG_VMS_RPC_SERVICE_HOST):$(VARLOG_VMS_RPC_SERVICE_PORT)"
        - name: VSN_HOME
          value: /varlog/data
        - name: COLLECTOR_NAME
          value: "otel"
        - name: COLLECTOR_ENDPOINT
          value: "localhost:4317"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            cpu: 1500m
            memory: 1500Mi
          requests:
            cpu: 1500m
            memory: 1500Mi
        volumeMounts:
        - name: varlog-sn-home
          mountPath: /varlog/data
        readinessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "/varlog/tools/grpc_health_probe -addr=${HOST_IP}:9091"
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "/varlog/tools/grpc_health_probe -addr=${HOST_IP}:9091"
          periodSeconds: 10
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - varlog-sn
      schedulerName: default-scheduler
      dnsConfig:
        nameservers:
        - 10.20.30.40
        searches:
        - dakao.io
        - krane.iwilab.com
        options:
        - name: timeout
          value: "1"
        - name: attempts
          value: "2"
        - name: rotate
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
