kind: Deployment
apiVersion: apps/v1
metadata:
  name: jaeger
  namespace: default
  labels:
    app: jaeger
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: jaeger
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 4000m
            memory: 4Gi
