apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

images:
- name: idock.daumkakao.io/varlog/varlog-mr
  newName: idock.daumkakao.io/varlog/varlog-mr
  newTag: IMAGE_TAG
- name: idock.daumkakao.io/varlog/varlog-sn
  newName: idock.daumkakao.io/varlog/varlog-sn
  newTag: IMAGE_TAG
- name: idock.daumkakao.io/varlog/varlog-vms
  newName: idock.daumkakao.io/varlog/varlog-vms
  newTag: IMAGE_TAG
- name: idock.daumkakao.io/varlog/rpc-test-server
  newName: idock.daumkakao.io/varlog/rpc-test-server
  newTag: IMAGE_TAG
- name: otel/opentelemetry-collector
  newName: mdock.daumkakao.io/otel/opentelemetry-collector
  newTag: 0.21.0
- name: jaegertracing/all-in-one
  newName: mdock.daumkakao.io/jaegertracing/all-in-one
  newTag: 1.22.0
- name: prom/prometheus
  newName: mdock.daumkakao.io/prom/prometheus
  newTag: v2.25.0
- name: busybox
  newName: mdock.daumkakao.io/busybox
  newTag: stable

patches:
- varlog-mr-data.yaml
- varlog-mr-clear-data.yaml
- varlog-sn-data.yaml
