run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - depguard
    - errcheck
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: golang.org/x/net/context
            desc: Should be replaced by standard lib context package
          - pkg: golang.org/x/exp/slog
            desc: Should be replaced by standard lib slog package
          - pkg: golang.org/x/exp/slices
            desc: Should be replaced by standard lib slices package
  godot:
    exclude:
      - "^ TODO"
      - "^ FIXME"
      - "^ NOTE"
      - "^ NB"
      - ":$"
      - "^[ ]*[-*]"
  goimports:
    local-prefixes: github.com/kakao/varlog
  misspell:
    locale: US
  revive:
    confidence: 0.1
    rules:
      - name: unhandled-error
        disabled: false
        arguments:
          - "fmt.Fprint"
          - "fmt.Fprintf"
          - "fmt.Fprintln"
          - "fmt.Print"
          - "fmt.Printf"
          - "fmt.Println"
          - "strings.Builder.WriteString"
          - "strings.Builder.WriteByte"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"
