version: "2"
linters:
  default: none
  enable:
    - depguard
    - errcheck
    - godot
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: golang.org/x/net/context
              desc: Should be replaced by standard lib 'context' package
            - pkg: golang.org/x/exp/slog
              desc: Should be replaced by standard lib 'slog' package
            - pkg: golang.org/x/exp/slices
              desc: Should be replaced by standard lib 'slices' package
            - pkg: go.uber.org/multierr
              desc: Should be replaced by standard lib 'errors' package
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib 'errors' package
    godot:
      exclude:
        - ^ TODO
        - ^ FIXME
        - ^ NOTE
        - ^ NB
        - :$
        - ^[ ]*[-*]
    misspell:
      locale: US
    revive:
      confidence: 0.1
      rules:
        - name: unhandled-error
          arguments:
            - fmt.Fprint
            - fmt.Fprintf
            - fmt.Fprintln
            - fmt.Print
            - fmt.Printf
            - fmt.Println
            - strings.Builder.WriteString
            - strings.Builder.WriteByte
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
    paths:
      - .*\.pb\.go$
      - .*_mock\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kakao/varlog
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*_mock\.go$
      - third_party$
      - builtin$
      - examples$
