package storage

import "github.com/kakao/varlog/pkg/types"

// CommitContext is metadata that represents the environment in which the
// commit is issued; for instance, the commit's version, the largest GLSN
// having the same commit version, and the commit range of this log stream.
type CommitContext struct {
	// Version is the unique identifier of the commit generated by the metadata
	// repository.
	Version types.Version
	// HighWatermark is the maximum GLSN in the versioned commit.
	HighWatermark types.GLSN
	// CommittedGLSNBegin is the start GLSN of this commit.
	CommittedGLSNBegin types.GLSN
	// CommittedGLSNEnd is the end GLSN of this commit exclusively.
	CommittedGLSNEnd types.GLSN
	// CommittedLLSNBegin is the starting LLSN of this commit.
	CommittedLLSNBegin types.LLSN
}

func (cc CommitContext) Empty() bool {
	return cc.CommittedGLSNEnd-cc.CommittedGLSNBegin == 0
}

func (cc CommitContext) Equal(other CommitContext) bool {
	return cc.Version == other.Version &&
		cc.CommittedGLSNBegin == other.CommittedGLSNBegin &&
		cc.CommittedGLSNEnd == other.CommittedGLSNEnd &&
		cc.CommittedLLSNBegin == other.CommittedLLSNBegin
}
