---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: varlogmr
  namespace: default
  labels:
    app.kubernetes.io/name: varlog
    app.kubernetes.io/component: mr
    app.kubernetes.io/part-of: varlog
spec:
  template:
    spec:
      volumes:
        - name: varlog-mr-home
          hostPath:
            path: /varlog/mr
            type: DirectoryOrCreate
      initContainers:
        - name: volume-perm
          volumeMounts:
            - name: varlog-mr-home
              mountPath: /varlog/mr
      containers:
        - name: varlog-mr
          resources:
            limits:
              cpu: 4000m
              memory: 4Gi
            requests:
              cpu: 4000m
              memory: 4Gi
          env:
            - name: VMR_HOME
              value: "/varlog/mr"
          volumeMounts:
            - name: varlog-mr-home
              mountPath: /varlog/mr
