apiVersion: v1
kind: Service
metadata:
    name: ms-rpc
spec:
    selector:
        app: ms
    ports:
        - name: rpc
          port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ms
    labels:
        app: ms
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ms
    template:
        metadata:
            labels:
                app: ms
        spec:
            containers:
                - name: ms
                  image: idock.daumkakao.io/jun_song/ms:0.0.1
                  imagePullPolicy: Always
                  ports:
                      - name: rpc
                        containerPort: 9090
                  command:
                      - "/varlog/bin/vms"
                      - "start"
                      - "--cluster-id"
                      - "1"
                      - "--replication-factor"
                      - "1"
                      - "--rpc-bind-address"
                      - "$(POD_IP):9090"
                      - "--mr-address"
                      - "$(MR_RPC_SERVICE_HOST):$(MR_RPC_SERVICE_PORT)"
                  env:
                      - name: POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                  readinessProbe:
                    tcpSocket:
                        port: 9090
            initContainers:
                - name: check-env
                  image: idock.daumkakao.io/jun_song/mc:0.0.1
                  imagePullPolicy: Always
                  command: ["/bin/sh", "-c", "echo ${MR_RPC_SERVICE_HOST}"]
