apiVersion: v1
kind: PersistentVolume
metadata:
    name: sn-pv-9
spec:
    storageClassName: local-storage
    local:
        path: /data
    capacity:
        storage: 1Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                          - dkosv3-varlog-sandbox-worker-9
