// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/mrpb/raft_metadata_repository.proto

package mrpb

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"

	github_com_kakao_varlog_pkg_types "github.com/kakao/varlog/pkg/types"
	snpb "github.com/kakao/varlog/proto/snpb"
	varlogpb "github.com/kakao/varlog/proto/varlogpb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LogStreamCommitResults struct {
	Version       github_com_kakao_varlog_pkg_types.Version `protobuf:"varint,1,opt,name=version,proto3,casttype=github.com/kakao/varlog/pkg/types.Version" json:"version,omitempty"`
	CommitResults []snpb.LogStreamCommitResult                         `protobuf:"bytes,3,rep,name=commit_results,json=commitResults,proto3" json:"commit_results"`
}

func (m *LogStreamCommitResults) Reset()         { *m = LogStreamCommitResults{} }
func (m *LogStreamCommitResults) String() string { return proto.CompactTextString(m) }
func (*LogStreamCommitResults) ProtoMessage()    {}
func (*LogStreamCommitResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_60447af781d89487, []int{0}
}
func (m *LogStreamCommitResults) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogStreamCommitResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogStreamCommitResults.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogStreamCommitResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStreamCommitResults.Merge(m, src)
}
func (m *LogStreamCommitResults) XXX_Size() int {
	return m.ProtoSize()
}
func (m *LogStreamCommitResults) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStreamCommitResults.DiscardUnknown(m)
}

var xxx_messageInfo_LogStreamCommitResults proto.InternalMessageInfo

func (m *LogStreamCommitResults) GetVersion() github_com_kakao_varlog_pkg_types.Version {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *LogStreamCommitResults) GetCommitResults() []snpb.LogStreamCommitResult {
	if m != nil {
		return m.CommitResults
	}
	return nil
}

type StorageNodeUncommitReport struct {
	StorageNodeID   github_com_kakao_varlog_pkg_types.StorageNodeID `protobuf:"varint,1,opt,name=storage_node_id,json=storageNodeId,proto3,casttype=github.com/kakao/varlog/pkg/types.StorageNodeID" json:"storage_node_id,omitempty"`
	UncommitReports []snpb.LogStreamUncommitReport                             `protobuf:"bytes,2,rep,name=uncommit_reports,json=uncommitReports,proto3" json:"uncommit_reports"`
}

func (m *StorageNodeUncommitReport) Reset()         { *m = StorageNodeUncommitReport{} }
func (m *StorageNodeUncommitReport) String() string { return proto.CompactTextString(m) }
func (*StorageNodeUncommitReport) ProtoMessage()    {}
func (*StorageNodeUncommitReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_60447af781d89487, []int{1}
}
func (m *StorageNodeUncommitReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StorageNodeUncommitReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StorageNodeUncommitReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StorageNodeUncommitReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageNodeUncommitReport.Merge(m, src)
}
func (m *StorageNodeUncommitReport) XXX_Size() int {
	return m.ProtoSize()
}
func (m *StorageNodeUncommitReport) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageNodeUncommitReport.DiscardUnknown(m)
}

var xxx_messageInfo_StorageNodeUncommitReport proto.InternalMessageInfo

func (m *StorageNodeUncommitReport) GetStorageNodeID() github_com_kakao_varlog_pkg_types.StorageNodeID {
	if m != nil {
		return m.StorageNodeID
	}
	return 0
}

func (m *StorageNodeUncommitReport) GetUncommitReports() []snpb.LogStreamUncommitReport {
	if m != nil {
		return m.UncommitReports
	}
	return nil
}

type LogStreamUncommitReports struct {
	Replicas map[github_com_kakao_varlog_pkg_types.StorageNodeID]snpb.LogStreamUncommitReport `protobuf:"bytes,1,rep,name=replicas,proto3,castkey=github.com/kakao/varlog/pkg/types.StorageNodeID" json:"replicas" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status   varlogpb.LogStreamStatus                                                                    `protobuf:"varint,2,opt,name=status,proto3,enum=varlog.varlogpb.LogStreamStatus" json:"status,omitempty"`
}

func (m *LogStreamUncommitReports) Reset()         { *m = LogStreamUncommitReports{} }
func (m *LogStreamUncommitReports) String() string { return proto.CompactTextString(m) }
func (*LogStreamUncommitReports) ProtoMessage()    {}
func (*LogStreamUncommitReports) Descriptor() ([]byte, []int) {
	return fileDescriptor_60447af781d89487, []int{2}
}
func (m *LogStreamUncommitReports) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogStreamUncommitReports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogStreamUncommitReports.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogStreamUncommitReports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStreamUncommitReports.Merge(m, src)
}
func (m *LogStreamUncommitReports) XXX_Size() int {
	return m.ProtoSize()
}
func (m *LogStreamUncommitReports) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStreamUncommitReports.DiscardUnknown(m)
}

var xxx_messageInfo_LogStreamUncommitReports proto.InternalMessageInfo

func (m *LogStreamUncommitReports) GetReplicas() map[github_com_kakao_varlog_pkg_types.StorageNodeID]snpb.LogStreamUncommitReport {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func (m *LogStreamUncommitReports) GetStatus() varlogpb.LogStreamStatus {
	if m != nil {
		return m.Status
	}
	return varlogpb.LogStreamStatusRunning
}

type MetadataRepositoryDescriptor struct {
	Metadata  *varlogpb.MetadataDescriptor                                   `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	LogStream *MetadataRepositoryDescriptor_LogStreamDescriptor              `protobuf:"bytes,2,opt,name=log_stream,json=logStream,proto3" json:"log_stream,omitempty"`
	PeersMap  MetadataRepositoryDescriptor_PeerDescriptorMap                 `protobuf:"bytes,3,opt,name=peers_map,json=peersMap,proto3" json:"peers_map"`
	Endpoints map[github_com_kakao_varlog_pkg_types.NodeID]string `protobuf:"bytes,4,rep,name=endpoints,proto3,castkey=github.com/kakao/varlog/pkg/types.NodeID" json:"endpoints,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *MetadataRepositoryDescriptor) Reset()         { *m = MetadataRepositoryDescriptor{} }
func (m *MetadataRepositoryDescriptor) String() string { return proto.CompactTextString(m) }
func (*MetadataRepositoryDescriptor) ProtoMessage()    {}
func (*MetadataRepositoryDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_60447af781d89487, []int{3}
}
func (m *MetadataRepositoryDescriptor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetadataRepositoryDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetadataRepositoryDescriptor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetadataRepositoryDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataRepositoryDescriptor.Merge(m, src)
}
func (m *MetadataRepositoryDescriptor) XXX_Size() int {
	return m.ProtoSize()
}
func (m *MetadataRepositoryDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataRepositoryDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataRepositoryDescriptor proto.InternalMessageInfo

func (m *MetadataRepositoryDescriptor) GetMetadata() *varlogpb.MetadataDescriptor {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MetadataRepositoryDescriptor) GetLogStream() *MetadataRepositoryDescriptor_LogStreamDescriptor {
	if m != nil {
		return m.LogStream
	}
	return nil
}

func (m *MetadataRepositoryDescriptor) GetPeersMap() MetadataRepositoryDescriptor_PeerDescriptorMap {
	if m != nil {
		return m.PeersMap
	}
	return MetadataRepositoryDescriptor_PeerDescriptorMap{}
}

func (m *MetadataRepositoryDescriptor) GetEndpoints() map[github_com_kakao_varlog_pkg_types.NodeID]string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type MetadataRepositoryDescriptor_LogStreamDescriptor struct {
	TrimVersion     github_com_kakao_varlog_pkg_types.Version                                   `protobuf:"varint,1,opt,name=trim_version,json=trimVersion,proto3,casttype=github.com/kakao/varlog/pkg/types.Version" json:"trim_version,omitempty"`
	CommitHistory   []*LogStreamCommitResults                                                              `protobuf:"bytes,2,rep,name=commit_history,json=commitHistory,proto3" json:"commit_history,omitempty"`
	UncommitReports map[github_com_kakao_varlog_pkg_types.LogStreamID]*LogStreamUncommitReports `protobuf:"bytes,3,rep,name=uncommit_reports,json=uncommitReports,proto3,castkey=github.com/kakao/varlog/pkg/types.LogStreamID" json:"uncommit_reports,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) Reset() {
	*m = MetadataRepositoryDescriptor_LogStreamDescriptor{}
}
func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) String() string {
	return proto.CompactTextString(m)
}
func (*MetadataRepositoryDescriptor_LogStreamDescriptor) ProtoMessage() {}
func (*MetadataRepositoryDescriptor_LogStreamDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_60447af781d89487, []int{3, 0}
}
func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetadataRepositoryDescriptor_LogStreamDescriptor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataRepositoryDescriptor_LogStreamDescriptor.Merge(m, src)
}
func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) XXX_Size() int {
	return m.ProtoSize()
}
func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataRepositoryDescriptor_LogStreamDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataRepositoryDescriptor_LogStreamDescriptor proto.InternalMessageInfo

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) GetTrimVersion() github_com_kakao_varlog_pkg_types.Version {
	if m != nil {
		return m.TrimVersion
	}
	return 0
}

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) GetCommitHistory() []*LogStreamCommitResults {
	if m != nil {
		return m.CommitHistory
	}
	return nil
}

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) GetUncommitReports() map[github_com_kakao_varlog_pkg_types.LogStreamID]*LogStreamUncommitReports {
	if m != nil {
		return m.UncommitReports
	}
	return nil
}

type MetadataRepositoryDescriptor_PeerDescriptor struct {
	URL       string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	IsLearner bool   `protobuf:"varint,2,opt,name=is_learner,json=isLearner,proto3" json:"is_learner,omitempty"`
}

func (m *MetadataRepositoryDescriptor_PeerDescriptor) Reset() {
	*m = MetadataRepositoryDescriptor_PeerDescriptor{}
}
func (m *MetadataRepositoryDescriptor_PeerDescriptor) String() string {
	return proto.CompactTextString(m)
}
func (*MetadataRepositoryDescriptor_PeerDescriptor) ProtoMessage() {}
func (*MetadataRepositoryDescriptor_PeerDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_60447af781d89487, []int{3, 1}
}
func (m *MetadataRepositoryDescriptor_PeerDescriptor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetadataRepositoryDescriptor_PeerDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetadataRepositoryDescriptor_PeerDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptor.Merge(m, src)
}
func (m *MetadataRepositoryDescriptor_PeerDescriptor) XXX_Size() int {
	return m.ProtoSize()
}
func (m *MetadataRepositoryDescriptor_PeerDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptor proto.InternalMessageInfo

func (m *MetadataRepositoryDescriptor_PeerDescriptor) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *MetadataRepositoryDescriptor_PeerDescriptor) GetIsLearner() bool {
	if m != nil {
		return m.IsLearner
	}
	return false
}

type MetadataRepositoryDescriptor_PeerDescriptorMap struct {
	Peers map[github_com_kakao_varlog_pkg_types.NodeID]*MetadataRepositoryDescriptor_PeerDescriptor `protobuf:"bytes,1,rep,name=peers,proto3,castkey=github.com/kakao/varlog/pkg/types.NodeID" json:"peers,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// applied_index is the AppliedIndex of RAFT that is updated by changing
	// configuration of members. For example, AddPeer and RemovePeer result
	// in increasing applied_index.
	AppliedIndex uint64 `protobuf:"varint,2,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
}

func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) Reset() {
	*m = MetadataRepositoryDescriptor_PeerDescriptorMap{}
}
func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) String() string {
	return proto.CompactTextString(m)
}
func (*MetadataRepositoryDescriptor_PeerDescriptorMap) ProtoMessage() {}
func (*MetadataRepositoryDescriptor_PeerDescriptorMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_60447af781d89487, []int{3, 2}
}
func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptorMap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptorMap.Merge(m, src)
}
func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) XXX_Size() int {
	return m.ProtoSize()
}
func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptorMap.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataRepositoryDescriptor_PeerDescriptorMap proto.InternalMessageInfo

func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) GetPeers() map[github_com_kakao_varlog_pkg_types.NodeID]*MetadataRepositoryDescriptor_PeerDescriptor {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) GetAppliedIndex() uint64 {
	if m != nil {
		return m.AppliedIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*LogStreamCommitResults)(nil), "varlog.mrpb.LogStreamCommitResults")
	proto.RegisterType((*StorageNodeUncommitReport)(nil), "varlog.mrpb.StorageNodeUncommitReport")
	proto.RegisterType((*LogStreamUncommitReports)(nil), "varlog.mrpb.LogStreamUncommitReports")
	proto.RegisterMapType((map[github_com_kakao_varlog_pkg_types.StorageNodeID]snpb.LogStreamUncommitReport)(nil), "varlog.mrpb.LogStreamUncommitReports.ReplicasEntry")
	proto.RegisterType((*MetadataRepositoryDescriptor)(nil), "varlog.mrpb.MetadataRepositoryDescriptor")
	proto.RegisterMapType((map[github_com_kakao_varlog_pkg_types.NodeID]string)(nil), "varlog.mrpb.MetadataRepositoryDescriptor.EndpointsEntry")
	proto.RegisterType((*MetadataRepositoryDescriptor_LogStreamDescriptor)(nil), "varlog.mrpb.MetadataRepositoryDescriptor.LogStreamDescriptor")
	proto.RegisterMapType((map[github_com_kakao_varlog_pkg_types.LogStreamID]*LogStreamUncommitReports)(nil), "varlog.mrpb.MetadataRepositoryDescriptor.LogStreamDescriptor.UncommitReportsEntry")
	proto.RegisterType((*MetadataRepositoryDescriptor_PeerDescriptor)(nil), "varlog.mrpb.MetadataRepositoryDescriptor.PeerDescriptor")
	proto.RegisterType((*MetadataRepositoryDescriptor_PeerDescriptorMap)(nil), "varlog.mrpb.MetadataRepositoryDescriptor.PeerDescriptorMap")
	proto.RegisterMapType((map[github_com_kakao_varlog_pkg_types.NodeID]*MetadataRepositoryDescriptor_PeerDescriptor)(nil), "varlog.mrpb.MetadataRepositoryDescriptor.PeerDescriptorMap.PeersEntry")
}

func init() {
	proto.RegisterFile("proto/mrpb/raft_metadata_repository.proto", fileDescriptor_60447af781d89487)
}

var fileDescriptor_60447af781d89487 = []byte{
	// 871 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0xc6, 0x4e, 0x1b, 0xbf, 0xd4, 0x69, 0x19, 0x2a, 0x70, 0x2d, 0xb0, 0xa3, 0x04, 0xa4,
	0x70, 0xe8, 0x5a, 0x4a, 0x90, 0xb0, 0xd2, 0x72, 0x31, 0x09, 0x10, 0x94, 0xb4, 0xd5, 0x44, 0xe1,
	0x00, 0x12, 0xab, 0xb1, 0x77, 0xea, 0xae, 0xb2, 0xbb, 0x33, 0x9a, 0x99, 0x0d, 0xf8, 0x9a, 0x7f,
	0x00, 0x24, 0xc4, 0xbd, 0xff, 0x07, 0x47, 0x38, 0xf4, 0x58, 0x89, 0x0b, 0x27, 0x47, 0x4a, 0x2e,
	0x48, 0x88, 0x7f, 0xa0, 0xe2, 0x80, 0x76, 0x66, 0xd6, 0xde, 0x25, 0x1b, 0xe4, 0x90, 0x9e, 0xbc,
	0xf3, 0xe3, 0xbd, 0xef, 0x7b, 0x6f, 0xbe, 0xef, 0xc9, 0xf0, 0x01, 0x17, 0x4c, 0xb1, 0x4e, 0x24,
	0x78, 0xbf, 0x23, 0xc8, 0x53, 0xe5, 0x45, 0x54, 0x11, 0x9f, 0x28, 0xe2, 0x09, 0xca, 0x99, 0x0c,
	0x14, 0x13, 0x23, 0x57, 0xdf, 0x41, 0x4b, 0xc7, 0x44, 0x84, 0x6c, 0xe8, 0xa6, 0x77, 0x9b, 0xf7,
	0x87, 0x81, 0x7a, 0x96, 0xf4, 0xdd, 0x01, 0x8b, 0x3a, 0x43, 0x36, 0x64, 0x1d, 0x7d, 0xa7, 0x9f,
	0x3c, 0xd5, 0x2b, 0x93, 0x34, 0xfd, 0x32, 0xb1, 0xcd, 0xb7, 0x4d, 0x2c, 0xef, 0x77, 0xb2, 0xfc,
	0xf6, 0xa0, 0x25, 0x63, 0xde, 0xef, 0x84, 0x6c, 0xe8, 0x49, 0x25, 0x28, 0x89, 0x34, 0xac, 0x50,
	0x54, 0x98, 0xf3, 0xd5, 0x5f, 0x1c, 0x78, 0x6b, 0x8f, 0x0d, 0x0f, 0xf4, 0xe1, 0x27, 0x2c, 0x8a,
	0x02, 0x85, 0xa9, 0x4c, 0x42, 0x25, 0x11, 0x86, 0x9b, 0xc7, 0x54, 0xc8, 0x80, 0xc5, 0x0d, 0x67,
	0xc5, 0x59, 0xaf, 0xf6, 0xba, 0xaf, 0xc6, 0xed, 0x0f, 0x2d, 0x2f, 0x9f, 0x24, 0xd1, 0x11, 0x39,
	0x22, 0x4c, 0x33, 0x34, 0xe8, 0xd9, 0x0f, 0x3f, 0x1a, 0x76, 0xd4, 0x88, 0x53, 0xe9, 0x7e, 0x69,
	0xe2, 0x71, 0x96, 0x08, 0x3d, 0x86, 0xe5, 0x81, 0x06, 0xf1, 0x84, 0x41, 0x69, 0x54, 0x56, 0x2a,
	0xeb, 0x4b, 0x1b, 0xab, 0xae, 0x2d, 0x3e, 0xa5, 0xeb, 0x96, 0x12, 0xea, 0x55, 0x5f, 0x8c, 0xdb,
	0x73, 0xb8, 0x3e, 0xc8, 0x93, 0xdc, 0xaa, 0xfe, 0xf1, 0xbc, 0xed, 0xac, 0xfe, 0xe9, 0xc0, 0xbd,
	0x03, 0xc5, 0x04, 0x19, 0xd2, 0x47, 0xcc, 0xa7, 0x87, 0x71, 0x76, 0x29, 0xad, 0x15, 0x7d, 0x0b,
	0xb7, 0xa5, 0x39, 0xf4, 0x62, 0xe6, 0x53, 0x2f, 0xf0, 0x75, 0x41, 0x0b, 0xbd, 0xc7, 0x67, 0xe3,
	0x76, 0x3d, 0x17, 0xb7, 0xbb, 0xfd, 0x6a, 0xdc, 0xde, 0xba, 0x52, 0x85, 0x85, 0x68, 0x5c, 0x97,
	0xb9, 0xa5, 0x8f, 0x0e, 0xe1, 0x4e, 0x12, 0x4f, 0xea, 0x4d, 0xb9, 0xc8, 0xc6, 0xbc, 0xae, 0xf7,
	0xbd, 0xf2, 0x7a, 0x8b, 0xc4, 0x6d, 0xc5, 0xb7, 0x93, 0xc2, 0xae, 0x5c, 0xfd, 0x6d, 0x1e, 0x1a,
	0x97, 0x84, 0x48, 0xf4, 0xa3, 0x03, 0x8b, 0x82, 0xf2, 0x30, 0x18, 0x10, 0xd9, 0x70, 0x34, 0xd8,
	0xa6, 0x9b, 0x53, 0xd6, 0x65, 0x60, 0xd2, 0xc5, 0x36, 0x6a, 0x27, 0x56, 0x62, 0xd4, 0xeb, 0xa5,
	0xd8, 0x27, 0xa7, 0xd7, 0x6a, 0xc7, 0x84, 0x08, 0xea, 0xc2, 0x0d, 0xa9, 0x88, 0x4a, 0xd2, 0xfa,
	0x9d, 0xf5, 0xe5, 0x8d, 0x95, 0x8c, 0x52, 0xa6, 0xdb, 0x29, 0xad, 0x03, 0x7d, 0x0f, 0xdb, 0xfb,
	0x4d, 0x02, 0xf5, 0x02, 0x31, 0x74, 0x07, 0x2a, 0x47, 0x74, 0x64, 0x5e, 0x10, 0xa7, 0x9f, 0x68,
	0x0b, 0x16, 0x8e, 0x49, 0x98, 0x50, 0x9d, 0x7b, 0xc6, 0xde, 0x62, 0x13, 0xb2, 0x35, 0xdf, 0x75,
	0xac, 0x86, 0xfe, 0x06, 0x78, 0x67, 0xdf, 0x9a, 0x07, 0x4f, 0xbc, 0xb9, 0x4d, 0xe5, 0x40, 0x04,
	0x5c, 0x31, 0x81, 0x76, 0x60, 0x31, 0x33, 0x97, 0x46, 0x5f, 0xda, 0x58, 0xbb, 0x50, 0x45, 0x96,
	0x60, 0x1a, 0xa6, 0x1f, 0xd1, 0xc1, 0x93, 0x50, 0xd4, 0x07, 0x98, 0xda, 0xd1, 0x52, 0xfe, 0xb8,
	0xf0, 0x42, 0xff, 0xc5, 0x62, 0x5a, 0xcf, 0x05, 0x88, 0x5a, 0x98, 0x1d, 0xa1, 0x6f, 0xa0, 0xc6,
	0x29, 0x15, 0xd2, 0x8b, 0x08, 0x6f, 0x54, 0x34, 0xc4, 0x83, 0xd9, 0x21, 0x9e, 0x50, 0x2a, 0xa6,
	0xcb, 0x7d, 0xc2, 0xad, 0x10, 0x17, 0x75, 0xce, 0x7d, 0xc2, 0xd1, 0xf7, 0x0e, 0xd4, 0x68, 0xec,
	0x73, 0x16, 0xc4, 0x4a, 0x36, 0xaa, 0x5a, 0x65, 0xdd, 0xd9, 0x01, 0x76, 0xb2, 0x50, 0x23, 0xb5,
	0x8f, 0x4e, 0x4e, 0xdb, 0x9b, 0x57, 0x92, 0x99, 0xd5, 0xd7, 0x94, 0x43, 0xf3, 0xaf, 0x0a, 0xbc,
	0x59, 0xd2, 0x1a, 0xf4, 0x35, 0xdc, 0x52, 0x22, 0x88, 0xbc, 0xd7, 0x35, 0xc9, 0x96, 0xd2, 0x6c,
	0x76, 0x81, 0x9e, 0x4c, 0xa6, 0xd9, 0xb3, 0x20, 0x75, 0xfe, 0xc8, 0xba, 0x7b, 0xad, 0xdc, 0x70,
	0x85, 0xf1, 0x6a, 0x1f, 0xcd, 0x8e, 0xb3, 0xcf, 0x4d, 0x3c, 0xfa, 0xd9, 0x29, 0x19, 0x19, 0x66,
	0x44, 0xe2, 0x6b, 0x69, 0xc4, 0xfd, 0x97, 0xdb, 0x4d, 0xe7, 0x1f, 0x9e, 0x9c, 0xb6, 0xbb, 0x57,
	0xea, 0xc3, 0x24, 0xf5, 0xee, 0xf6, 0x85, 0xc1, 0xd4, 0x0c, 0xe0, 0x6e, 0x19, 0x4c, 0x89, 0x65,
	0x1f, 0x14, 0x2d, 0xfb, 0xfe, 0x4c, 0x13, 0x2a, 0xe7, 0xd9, 0xe6, 0x17, 0xb0, 0x5c, 0x94, 0x29,
	0xba, 0x07, 0x95, 0x44, 0x84, 0x1a, 0xa4, 0xd6, 0xbb, 0x79, 0x36, 0x6e, 0x57, 0x0e, 0xf1, 0x1e,
	0x4e, 0xf7, 0xd0, 0xbb, 0x00, 0x81, 0xf4, 0x42, 0x4a, 0x44, 0x4c, 0x85, 0x86, 0x5c, 0xc4, 0xb5,
	0x40, 0xee, 0x99, 0x8d, 0xe6, 0xaf, 0xf3, 0xf0, 0xc6, 0x05, 0xcd, 0xa3, 0x9f, 0x1c, 0x58, 0xd0,
	0x82, 0xb7, 0x53, 0xf4, 0xd3, 0x6b, 0x18, 0x48, 0xef, 0x5c, 0x57, 0xed, 0x86, 0x0d, 0x5a, 0x83,
	0x3a, 0xe1, 0x3c, 0x0c, 0xa8, 0xef, 0x05, 0xb1, 0x4f, 0xbf, 0xd3, 0xf5, 0x54, 0xf1, 0x2d, 0xbb,
	0xb9, 0x9b, 0xee, 0x35, 0x05, 0xc0, 0x14, 0x32, 0xdf, 0xff, 0xaa, 0xe9, 0xff, 0xa3, 0x62, 0xff,
	0xbb, 0xff, 0xb7, 0xb6, 0xfc, 0x93, 0x3c, 0x84, 0xe5, 0xa2, 0xb1, 0x4b, 0x70, 0xef, 0xe6, 0x71,
	0x6b, 0xb9, 0xe8, 0xde, 0x67, 0x2f, 0xce, 0x5a, 0xce, 0xcb, 0xb3, 0x96, 0xf3, 0xc3, 0x79, 0x6b,
	0xee, 0xf9, 0x79, 0xcb, 0x79, 0x79, 0xde, 0x9a, 0xfb, 0xfd, 0xbc, 0x35, 0xf7, 0xd5, 0xfd, 0x59,
	0x9a, 0x35, 0xf9, 0x97, 0xd5, 0xbf, 0xa1, 0xbf, 0x37, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x64,
	0xd8, 0xc2, 0xf8, 0x7a, 0x09, 0x00, 0x00,
}

func (this *LogStreamCommitResults) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LogStreamCommitResults)
	if !ok {
		that2, ok := that.(LogStreamCommitResults)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if len(this.CommitResults) != len(that1.CommitResults) {
		return false
	}
	for i := range this.CommitResults {
		if !this.CommitResults[i].Equal(&that1.CommitResults[i]) {
			return false
		}
	}
	return true
}
func (this *LogStreamUncommitReports) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LogStreamUncommitReports)
	if !ok {
		that2, ok := that.(LogStreamUncommitReports)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Replicas) != len(that1.Replicas) {
		return false
	}
	for i := range this.Replicas {
		a := this.Replicas[i]
		b := that1.Replicas[i]
		if !(&a).Equal(&b) {
			return false
		}
	}
	if this.Status != that1.Status {
		return false
	}
	return true
}
func (m *LogStreamCommitResults) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogStreamCommitResults) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LogStreamCommitResults) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommitResults) > 0 {
		for iNdEx := len(m.CommitResults) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitResults[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Version != 0 {
		i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StorageNodeUncommitReport) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StorageNodeUncommitReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StorageNodeUncommitReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UncommitReports) > 0 {
		for iNdEx := len(m.UncommitReports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UncommitReports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.StorageNodeID != 0 {
		i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(m.StorageNodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LogStreamUncommitReports) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogStreamUncommitReports) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LogStreamUncommitReports) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Replicas) > 0 {
		for k := range m.Replicas {
			v := m.Replicas[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MetadataRepositoryDescriptor) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetadataRepositoryDescriptor) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetadataRepositoryDescriptor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Endpoints) > 0 {
		for k := range m.Endpoints {
			v := m.Endpoints[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.PeersMap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.LogStream != nil {
		{
			size, err := m.LogStream.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UncommitReports) > 0 {
		for k := range m.UncommitReports {
			v := m.UncommitReports[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.CommitHistory) > 0 {
		for iNdEx := len(m.CommitHistory) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommitHistory[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TrimVersion != 0 {
		i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(m.TrimVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MetadataRepositoryDescriptor_PeerDescriptor) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetadataRepositoryDescriptor_PeerDescriptor) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetadataRepositoryDescriptor_PeerDescriptor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsLearner {
		i--
		if m.IsLearner {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.URL) > 0 {
		i -= len(m.URL)
		copy(dAtA[i:], m.URL)
		i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(len(m.URL)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AppliedIndex != 0 {
		i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(m.AppliedIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Peers) > 0 {
		for k := range m.Peers {
			v := m.Peers[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintRaftMetadataRepository(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintRaftMetadataRepository(dAtA []byte, offset int, v uint64) int {
	offset -= sovRaftMetadataRepository(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LogStreamCommitResults) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovRaftMetadataRepository(uint64(m.Version))
	}
	if len(m.CommitResults) > 0 {
		for _, e := range m.CommitResults {
			l = e.ProtoSize()
			n += 1 + l + sovRaftMetadataRepository(uint64(l))
		}
	}
	return n
}

func (m *StorageNodeUncommitReport) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StorageNodeID != 0 {
		n += 1 + sovRaftMetadataRepository(uint64(m.StorageNodeID))
	}
	if len(m.UncommitReports) > 0 {
		for _, e := range m.UncommitReports {
			l = e.ProtoSize()
			n += 1 + l + sovRaftMetadataRepository(uint64(l))
		}
	}
	return n
}

func (m *LogStreamUncommitReports) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Replicas) > 0 {
		for k, v := range m.Replicas {
			_ = k
			_ = v
			l = v.ProtoSize()
			mapEntrySize := 1 + sovRaftMetadataRepository(uint64(k)) + 1 + l + sovRaftMetadataRepository(uint64(l))
			n += mapEntrySize + 1 + sovRaftMetadataRepository(uint64(mapEntrySize))
		}
	}
	if m.Status != 0 {
		n += 1 + sovRaftMetadataRepository(uint64(m.Status))
	}
	return n
}

func (m *MetadataRepositoryDescriptor) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Metadata != nil {
		l = m.Metadata.ProtoSize()
		n += 1 + l + sovRaftMetadataRepository(uint64(l))
	}
	if m.LogStream != nil {
		l = m.LogStream.ProtoSize()
		n += 1 + l + sovRaftMetadataRepository(uint64(l))
	}
	l = m.PeersMap.ProtoSize()
	n += 1 + l + sovRaftMetadataRepository(uint64(l))
	if len(m.Endpoints) > 0 {
		for k, v := range m.Endpoints {
			_ = k
			_ = v
			mapEntrySize := 1 + sovRaftMetadataRepository(uint64(k)) + 1 + len(v) + sovRaftMetadataRepository(uint64(len(v)))
			n += mapEntrySize + 1 + sovRaftMetadataRepository(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrimVersion != 0 {
		n += 1 + sovRaftMetadataRepository(uint64(m.TrimVersion))
	}
	if len(m.CommitHistory) > 0 {
		for _, e := range m.CommitHistory {
			l = e.ProtoSize()
			n += 1 + l + sovRaftMetadataRepository(uint64(l))
		}
	}
	if len(m.UncommitReports) > 0 {
		for k, v := range m.UncommitReports {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.ProtoSize()
				l += 1 + sovRaftMetadataRepository(uint64(l))
			}
			mapEntrySize := 1 + sovRaftMetadataRepository(uint64(k)) + l
			n += mapEntrySize + 1 + sovRaftMetadataRepository(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *MetadataRepositoryDescriptor_PeerDescriptor) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.URL)
	if l > 0 {
		n += 1 + l + sovRaftMetadataRepository(uint64(l))
	}
	if m.IsLearner {
		n += 2
	}
	return n
}

func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Peers) > 0 {
		for k, v := range m.Peers {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.ProtoSize()
				l += 1 + sovRaftMetadataRepository(uint64(l))
			}
			mapEntrySize := 1 + sovRaftMetadataRepository(uint64(k)) + l
			n += mapEntrySize + 1 + sovRaftMetadataRepository(uint64(mapEntrySize))
		}
	}
	if m.AppliedIndex != 0 {
		n += 1 + sovRaftMetadataRepository(uint64(m.AppliedIndex))
	}
	return n
}

func sovRaftMetadataRepository(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRaftMetadataRepository(x uint64) (n int) {
	return sovRaftMetadataRepository(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LogStreamCommitResults) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogStreamCommitResults: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogStreamCommitResults: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= github_com_kakao_varlog_pkg_types.Version(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitResults", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitResults = append(m.CommitResults, snpb.LogStreamCommitResult{})
			if err := m.CommitResults[len(m.CommitResults)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StorageNodeUncommitReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StorageNodeUncommitReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StorageNodeUncommitReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageNodeID", wireType)
			}
			m.StorageNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageNodeID |= github_com_kakao_varlog_pkg_types.StorageNodeID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UncommitReports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UncommitReports = append(m.UncommitReports, snpb.LogStreamUncommitReport{})
			if err := m.UncommitReports[len(m.UncommitReports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LogStreamUncommitReports) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogStreamUncommitReports: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogStreamUncommitReports: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Replicas == nil {
				m.Replicas = make(map[github_com_kakao_varlog_pkg_types.StorageNodeID]snpb.LogStreamUncommitReport)
			}
			var mapkey int32
			mapvalue := &snpb.LogStreamUncommitReport{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftMetadataRepository
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &snpb.LogStreamUncommitReport{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Replicas[github_com_kakao_varlog_pkg_types.StorageNodeID(mapkey)] = *mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= varlogpb.LogStreamStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetadataRepositoryDescriptor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetadataRepositoryDescriptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetadataRepositoryDescriptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &varlogpb.MetadataDescriptor{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogStream", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LogStream == nil {
				m.LogStream = &MetadataRepositoryDescriptor_LogStreamDescriptor{}
			}
			if err := m.LogStream.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeersMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PeersMap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endpoints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Endpoints == nil {
				m.Endpoints = make(map[github_com_kakao_varlog_pkg_types.NodeID]string)
			}
			var mapkey uint64
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftMetadataRepository
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Endpoints[github_com_kakao_varlog_pkg_types.NodeID(mapkey)] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetadataRepositoryDescriptor_LogStreamDescriptor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogStreamDescriptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogStreamDescriptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrimVersion", wireType)
			}
			m.TrimVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrimVersion |= github_com_kakao_varlog_pkg_types.Version(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitHistory = append(m.CommitHistory, &LogStreamCommitResults{})
			if err := m.CommitHistory[len(m.CommitHistory)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UncommitReports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UncommitReports == nil {
				m.UncommitReports = make(map[github_com_kakao_varlog_pkg_types.LogStreamID]*LogStreamUncommitReports)
			}
			var mapkey int32
			var mapvalue *LogStreamUncommitReports
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftMetadataRepository
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &LogStreamUncommitReports{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.UncommitReports[github_com_kakao_varlog_pkg_types.LogStreamID(mapkey)] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetadataRepositoryDescriptor_PeerDescriptor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PeerDescriptor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PeerDescriptor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.URL = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsLearner", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsLearner = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetadataRepositoryDescriptor_PeerDescriptorMap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PeerDescriptorMap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PeerDescriptorMap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Peers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Peers == nil {
				m.Peers = make(map[github_com_kakao_varlog_pkg_types.NodeID]*MetadataRepositoryDescriptor_PeerDescriptor)
			}
			var mapkey uint64
			var mapvalue *MetadataRepositoryDescriptor_PeerDescriptor
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRaftMetadataRepository
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRaftMetadataRepository
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &MetadataRepositoryDescriptor_PeerDescriptor{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthRaftMetadataRepository
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Peers[github_com_kakao_varlog_pkg_types.NodeID(mapkey)] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppliedIndex", wireType)
			}
			m.AppliedIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppliedIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRaftMetadataRepository(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRaftMetadataRepository
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRaftMetadataRepository(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRaftMetadataRepository
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRaftMetadataRepository
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRaftMetadataRepository
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRaftMetadataRepository
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRaftMetadataRepository
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRaftMetadataRepository        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRaftMetadataRepository          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRaftMetadataRepository = fmt.Errorf("proto: unexpected end of group")
)
