---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: busybox
    newName: mdock.daumkakao.io/busybox
    newTag: stable

resources:
  - ../../base/clear
  - varlogmr-clear-patch.yaml
  - varlogsn-clear-patch.yaml
