---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: varlogsn-clear
  namespace: default
  labels:
    app: varlogsn-clear
    name: varlogsn-clear
spec:
  template:
    spec:
      volumes:
        - name: varlogsn-data
          $patch: delete
        - name: varlogsn-data01
          hostPath:
            path: /data1/varlog/sn
            type: DirectoryOrCreate
        - name: varlogsn-data02
          hostPath:
            path: /data2/varlog/sn
            type: DirectoryOrCreate
        - name: varlogsn-data03
          hostPath:
            path: /data3/varlog/sn
            type: DirectoryOrCreate
        - name: varlogsn-data04
          hostPath:
            path: /data4/varlog/sn
            type: DirectoryOrCreate
      initContainers:
        - name: rm-varlogsn-data
          command:
            - "sh"
            - "-c"
            - "rm -rf /data[1-4]/varlog/sn/data"
          volumeMounts:
            - name: varlogsn-data
              $patch: delete
            - name: varlogsn-data01
              mountPath: /data1/varlog/sn
            - name: varlogsn-data02
              mountPath: /data2/varlog/sn
            - name: varlogsn-data03
              mountPath: /data3/varlog/sn
            - name: varlogsn-data04
              mountPath: /data4/varlog/sn
      containers:
        - name: varlogsn-clear
          command:
            - "sh"
            - "-c"
            - |
              [ ! -d /data1/varlog/sn/data ] &&
              [ ! -d /data2/varlog/sn/data ] &&
              [ ! -d /data3/varlog/sn/data ] &&
              [ ! -d /data4/varlog/sn/data ] &&
              echo varlogsn data directories are clean
          volumeMounts:
            - name: varlogsn-data
              $patch: delete
            - name: varlogsn-data01
              mountPath: /data1/varlog/sn
            - name: varlogsn-data02
              mountPath: /data2/varlog/sn
            - name: varlogsn-data03
              mountPath: /data3/varlog/sn
            - name: varlogsn-data04
              mountPath: /data4/varlog/sn
