---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: varlogmr-clear
  namespace: default
  labels:
    app: varlogmr-clear
    name: varlogmr-clear
spec:
  template:
    spec:
      volumes:
        - name: varlogmr-data
          hostPath:
            path: /data1/varlog/mr
            type: DirectoryOrCreate
      initContainers:
        - name: rm-varlogmr-data
          command:
            - "sh"
            - "-c"
            - "rm -rf /data1/varlog/mr/raftdata"
          volumeMounts:
            - name: varlogmr-data
              mountPath: /data1/varlog/mr
      containers:
        - name: varlogmr-clear
          command:
            - "sh"
            - "-c"
            - "[ ! -d /data1/varlog/mr/raftdata ] && echo /data1/varlog/mr/raftdata is clean"
          volumeMounts:
            - name: varlogmr-data
              mountPath: /data1/varlog/mr
