pipeline {

  agent any

  stages {

    stage("build") {
      steps {
        sh "make all"
      }
    }

    stage("test") {
      environment { 
        TEST_USE_LOGGER = "0"
      }

      steps {
        sh "make test TEST_FAILFAST=1 TEST_TIMEOUT=30m TEST_CPU=4,8,16 TEST_COUNT=1 TEST_COVERAGE=1"
      }

      post {
        always {
          sh "make test_report"
          sh "make coverage_report"
          junit "build/reports/*.xml"
          cobertura coberturaReportFile: "build/reports/coverage.xml"
        }
      }

    }

  }

}
