pipeline {

  agent any

  stages {

    stage("build") {
      steps {
        sh "make all"
      }
    }

    stage("test") {
      environment { 
        TEST_USE_LOGGER = "0"
      }

      steps {
        sh "make test TEST_FAILFAST=1 TEST_TIMEOUT=20m TEST_COUNT=3 TEST_COVERAGE=1"
      }

      post {
        always {
          sh "make test_report"
          junit "build/reports/*.xml"

          sh "make coverage_report"
          cobertura coberturaReportFile: "build/reports/coverage.xml"
        }
      }
    }

    stage("benchmark") {
      environment {
        TEST_USE_LOGGER = "0"
      }

      steps {
        sh "make bench"

        lock("varlog-sandbox-01") {
          sh "./scripts/benchmark.sh > build/reports/load.xml"
        }
      }

      post {
        always {
          sh "make bench_report"
          perfReport "build/reports/bench.xml"
          perfReport "build/reports/load.xml"
        }
      }
    }

  }

}
