kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: otel-agent
  namespace: default
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  template:
    spec:
      containers:
        - name: otel-agent
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
