apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: varlog-mr-clear
  namespace: default
  labels:
    app: varlog-mr-clear
    name: varlog-mr-clear
spec:
  template:
    spec:
      volumes:
        - name: varlog-mr-home
          hostPath:
            path: /varlog/mr
            type: DirectoryOrCreate
