apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: busybox
  newName: mdock.daumkakao.io/busybox
  newTag: stable
- name: idock.daumkakao.io/varlog/all-in-one
  newName: idock.daumkakao.io/varlog/all-in-one
  newTag: v0.1.5-0aabea2e

resources:
- ../../base/varlogadm
