apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

images:
- name: idock.daumkakao.io/varlog/all-in-one
  newName: idock.daumkakao.io/varlog/all-in-one
  newTag: IMAGE_TAG
- name: idock.daumkakao.io/varlog/rpc-test-server
  newName: idock.daumkakao.io/varlog/rpc-test-server
  newTag: IMAGE_TAG
- name: otel/opentelemetry-collector
  newName: mdock.daumkakao.io/otel/opentelemetry-collector
  newTag: 0.34.0
- name: jaegertracing/all-in-one
  newName: mdock.daumkakao.io/jaegertracing/all-in-one
  newTag: 1.26.0
- name: prom/prometheus
  newName: mdock.daumkakao.io/prom/prometheus
  newTag: v2.30.0
- name: busybox
  newName: mdock.daumkakao.io/busybox
  newTag: stable

patches:
- varlog-mr-patch.yaml
- varlog-mr-clear-patch.yaml
- varlog-sn-patch.yaml
- otel-agent-patch.yaml
- otel-collector-patch.yaml
- jaeger-patch.yaml
- prometheus-patch.yaml
