apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: busybox
  newName: mdock.daumkakao.io/busybox
  newTag: stable
- name: idock.daumkakao.io/varlog/all-in-one
  newName: idock.daumkakao.io/varlog/all-in-one
  newTag: v0.1.6-9b13d96d

patchesStrategicMerge:
- varlogmr-patch.yaml
- varlogmr-clear-patch.yaml
- varlogsn-patch.yaml
