kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: varlogmr
  namespace: default
  labels:
    app: varlogmr
    name: varlogmr
spec:
  template:
    spec:
      containers:
        - name: varlogmr
          resources:
            limits:
              cpu: 4000m
              memory: 4Gi
            requests:
              cpu: 4000m
              memory: 4Gi
