---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varlogadm
  namespace: default
  labels:
    app.kubernetes.io/name: varlog
    app.kubernetes.io/component: varlogadm
    app.kubernetes.io/part-of: varlog
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: varlogadm
          resources:
            requests:
              cpu: 1000m
              memory: 1000Mi
            limits:
              cpu: 4000m
              memory: 4000Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: dkosv3.9rum.cc/node-group
                    operator: In
                    values:
                      - varlogadm
