kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: varlogmr-clear
  namespace: default
  labels:
    app: varlogmr-clear
    name: varlogmr-clear
spec:
  template:
    spec:
      volumes:
        - name: varlogmr-home
          hostPath:
            path: /varlog/mr
            type: DirectoryOrCreate
