kind: Deployment
apiVersion: apps/v1
metadata:
  name: jaeger
  namespace: default
  labels:
    app: jaeger
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: jaeger
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
