kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
spec:
  replicas: 0
  template:
    spec:
      containers:
        - name: prometheus
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
