kind: Deployment
apiVersion: apps/v1
metadata:
  name: otel-collector
  namespace: default
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: otel-collector
        resources:
          limits:
            cpu: 8000m
            memory: 16Gi
          requests:
            cpu: 8000m
            memory: 16Gi
