kind: ConfigMap
apiVersion: v1
metadata:
  name: otel-agent-conf
  labels:
    app: opentelemetry
    component: otel-agent-conf

data:
  otel-agent-config: |
    receivers:
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          disk:
          load:
          filesystem:
          memory:
          network:
          process:
            include:
              names: [vmr, vsn]
              match_type: strict
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: "otel-collector.default:4317"
        insecure: true

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 20
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [hostmetrics, otlp]
          processors: [batch]
          exporters: [otlp]
      extensions: [health_check, pprof, zpages]
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: otel-agent
  namespace: default
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  template:
    spec:
      containers:
      - name: otel-agent
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 2000m
            memory: 4Gi
