kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: prometheus
        resources:
          limits:
            cpu: 8000m
            memory: 16Gi
          requests:
            cpu: 8000m
            memory: 16Gi
