kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: varlog-vms
  labels:
    app: varlog-vms
spec:
  template:
    spec:
      containers:
      - name: varlog-vms
        resources:
          limits:
            cpu: 4000m
            memory: 8Gi
          requests:
            cpu: 4000m
            memory: 8Gi
