kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: varlog-mr
  namespace: default
  labels:
    app: varlog-mr
    name: varlog-mr
spec:
  template:
    spec:
      volumes:
      - name: varlog-mr-home
        hostPath:
          path: /data1/varlog/mr
          type: DirectoryOrCreate
      initContainers:
      - name: volume-perm
        command:
        - "sh"
        - "-c"
        - "chmod -R 777 /data1/varlog/mr"
        volumeMounts:
        - name: varlog-mr-home 
          mountPath: /data1/varlog/mr
      containers:
      - name: varlog-mr
        resources:
          limits:
            cpu: 16000m
            memory: 32Gi
          requests:
            cpu: 16000m
            memory: 32Gi
        env:
        - name: VMR_HOME
          value: "/data1/varlog/mr"
        volumeMounts:
        - name: varlog-mr-home
          mountPath: /data1/varlog/mr
