package snpb

//go:generate mockgen -build_flags -mod=vendor -package mock -destination mock/snpb_mock.go . ReplicatorServiceClient,ReplicatorServiceServer,ReplicatorService_ReplicateClient,ReplicatorService_ReplicateServer,LogIOClient,LogIOServer,LogIO_SubscribeClient,LogIO_SubscribeServer,LogStreamReporterServiceClient,LogStreamReporterServiceServer,ManagementClient,ManagementServer
