// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: replicator.proto

package snpb

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_daumkakao_com_varlog_varlog_pkg_varlog_types "github.daumkakao.com/varlog/varlog/pkg/varlog/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	strconv "strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SyncState int32

const (
	SyncStateError      SyncState = 0
	SyncStateInProgress SyncState = 1
	SyncStateComplete   SyncState = 2
)

var SyncState_name = map[int32]string{
	0: "ERROR",
	1: "IN_PROGRESS",
	2: "COMPLETE",
}

var SyncState_value = map[string]int32{
	"ERROR":       0,
	"IN_PROGRESS": 1,
	"COMPLETE":    2,
}

func (SyncState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{0}
}

// ReplicationRequest contains LLSN (Local Log Sequence Number) that indicates
// a log position in the local log stream of the primary storage node.
type ReplicationRequest struct {
	LogStreamID          github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID `protobuf:"varint,1,opt,name=log_stream_id,json=logStreamId,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.LogStreamID" json:"log_stream_id,omitempty"`
	LLSN                 github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN        `protobuf:"varint,2,opt,name=llsn,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.LLSN" json:"llsn,omitempty"`
	Payload              []byte                                                          `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                        `json:"-"`
	XXX_unrecognized     []byte                                                          `json:"-"`
	XXX_sizecache        int32                                                           `json:"-"`
}

func (m *ReplicationRequest) Reset()         { *m = ReplicationRequest{} }
func (m *ReplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicationRequest) ProtoMessage()    {}
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{0}
}
func (m *ReplicationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReplicationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationRequest.Merge(m, src)
}
func (m *ReplicationRequest) XXX_Size() int {
	return m.ProtoSize()
}
func (m *ReplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationRequest proto.InternalMessageInfo

func (m *ReplicationRequest) GetLogStreamID() github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID {
	if m != nil {
		return m.LogStreamID
	}
	return 0
}

func (m *ReplicationRequest) GetLLSN() github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN {
	if m != nil {
		return m.LLSN
	}
	return 0
}

func (m *ReplicationRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// ReplicationResponse indicates that a log entry at given LLSN is replicated.
type ReplicationResponse struct {
	StorageNodeID        github_daumkakao_com_varlog_varlog_pkg_varlog_types.StorageNodeID `protobuf:"varint,1,opt,name=storage_node_id,json=storageNodeId,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.StorageNodeID" json:"storage_node_id,omitempty"`
	LogStreamID          github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID   `protobuf:"varint,2,opt,name=log_stream_id,json=logStreamId,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.LogStreamID" json:"log_stream_id,omitempty"`
	LLSN                 github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN          `protobuf:"varint,3,opt,name=llsn,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.LLSN" json:"llsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                          `json:"-"`
	XXX_unrecognized     []byte                                                            `json:"-"`
	XXX_sizecache        int32                                                             `json:"-"`
}

func (m *ReplicationResponse) Reset()         { *m = ReplicationResponse{} }
func (m *ReplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicationResponse) ProtoMessage()    {}
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{1}
}
func (m *ReplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationResponse.Merge(m, src)
}
func (m *ReplicationResponse) XXX_Size() int {
	return m.ProtoSize()
}
func (m *ReplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationResponse proto.InternalMessageInfo

func (m *ReplicationResponse) GetStorageNodeID() github_daumkakao_com_varlog_varlog_pkg_varlog_types.StorageNodeID {
	if m != nil {
		return m.StorageNodeID
	}
	return 0
}

func (m *ReplicationResponse) GetLogStreamID() github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID {
	if m != nil {
		return m.LogStreamID
	}
	return 0
}

func (m *ReplicationResponse) GetLLSN() github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN {
	if m != nil {
		return m.LLSN
	}
	return 0
}

type SyncPosition struct {
	LLSN                 github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN `protobuf:"varint,1,opt,name=llsn,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.LLSN" json:"llsn,omitempty"`
	GLSN                 github_daumkakao_com_varlog_varlog_pkg_varlog_types.GLSN `protobuf:"varint,2,opt,name=glsn,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.GLSN" json:"glsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *SyncPosition) Reset()         { *m = SyncPosition{} }
func (m *SyncPosition) String() string { return proto.CompactTextString(m) }
func (*SyncPosition) ProtoMessage()    {}
func (*SyncPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{2}
}
func (m *SyncPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPosition.Merge(m, src)
}
func (m *SyncPosition) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPosition.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPosition proto.InternalMessageInfo

func (m *SyncPosition) GetLLSN() github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN {
	if m != nil {
		return m.LLSN
	}
	return 0
}

func (m *SyncPosition) GetGLSN() github_daumkakao_com_varlog_varlog_pkg_varlog_types.GLSN {
	if m != nil {
		return m.GLSN
	}
	return 0
}

type SyncStatus struct {
	State                SyncState    `protobuf:"varint,1,opt,name=state,proto3,enum=varlog.snpb.SyncState" json:"state,omitempty"`
	First                SyncPosition `protobuf:"bytes,2,opt,name=first,proto3" json:"first"`
	Last                 SyncPosition `protobuf:"bytes,3,opt,name=last,proto3" json:"last"`
	Current              SyncPosition `protobuf:"bytes,4,opt,name=current,proto3" json:"current"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncStatus) Reset()         { *m = SyncStatus{} }
func (m *SyncStatus) String() string { return proto.CompactTextString(m) }
func (*SyncStatus) ProtoMessage()    {}
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{3}
}
func (m *SyncStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatus.Merge(m, src)
}
func (m *SyncStatus) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatus proto.InternalMessageInfo

func (m *SyncStatus) GetState() SyncState {
	if m != nil {
		return m.State
	}
	return SyncStateError
}

func (m *SyncStatus) GetFirst() SyncPosition {
	if m != nil {
		return m.First
	}
	return SyncPosition{}
}

func (m *SyncStatus) GetLast() SyncPosition {
	if m != nil {
		return m.Last
	}
	return SyncPosition{}
}

func (m *SyncStatus) GetCurrent() SyncPosition {
	if m != nil {
		return m.Current
	}
	return SyncPosition{}
}

type SyncReplicateRequest struct {
	First                SyncPosition                                                    `protobuf:"bytes,1,opt,name=first,proto3" json:"first"`
	Last                 SyncPosition                                                    `protobuf:"bytes,2,opt,name=last,proto3" json:"last"`
	Current              SyncPosition                                                    `protobuf:"bytes,3,opt,name=current,proto3" json:"current"`
	Data                 []byte                                                          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	LogStreamID          github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID `protobuf:"varint,5,opt,name=log_stream_id,json=logStreamId,proto3,casttype=github.daumkakao.com/varlog/varlog/pkg/varlog/types.LogStreamID" json:"log_stream_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                        `json:"-"`
	XXX_unrecognized     []byte                                                          `json:"-"`
	XXX_sizecache        int32                                                           `json:"-"`
}

func (m *SyncReplicateRequest) Reset()         { *m = SyncReplicateRequest{} }
func (m *SyncReplicateRequest) String() string { return proto.CompactTextString(m) }
func (*SyncReplicateRequest) ProtoMessage()    {}
func (*SyncReplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{4}
}
func (m *SyncReplicateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncReplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncReplicateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncReplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReplicateRequest.Merge(m, src)
}
func (m *SyncReplicateRequest) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncReplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReplicateRequest proto.InternalMessageInfo

func (m *SyncReplicateRequest) GetFirst() SyncPosition {
	if m != nil {
		return m.First
	}
	return SyncPosition{}
}

func (m *SyncReplicateRequest) GetLast() SyncPosition {
	if m != nil {
		return m.Last
	}
	return SyncPosition{}
}

func (m *SyncReplicateRequest) GetCurrent() SyncPosition {
	if m != nil {
		return m.Current
	}
	return SyncPosition{}
}

func (m *SyncReplicateRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SyncReplicateRequest) GetLogStreamID() github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID {
	if m != nil {
		return m.LogStreamID
	}
	return 0
}

type SyncReplicateResponse struct {
	Status               *SyncStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SyncReplicateResponse) Reset()         { *m = SyncReplicateResponse{} }
func (m *SyncReplicateResponse) String() string { return proto.CompactTextString(m) }
func (*SyncReplicateResponse) ProtoMessage()    {}
func (*SyncReplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{5}
}
func (m *SyncReplicateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncReplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncReplicateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncReplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReplicateResponse.Merge(m, src)
}
func (m *SyncReplicateResponse) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncReplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReplicateResponse proto.InternalMessageInfo

func (m *SyncReplicateResponse) GetStatus() *SyncStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("varlog.snpb.SyncState", SyncState_name, SyncState_value)
	proto.RegisterType((*ReplicationRequest)(nil), "varlog.snpb.ReplicationRequest")
	proto.RegisterType((*ReplicationResponse)(nil), "varlog.snpb.ReplicationResponse")
	proto.RegisterType((*SyncPosition)(nil), "varlog.snpb.SyncPosition")
	proto.RegisterType((*SyncStatus)(nil), "varlog.snpb.SyncStatus")
	proto.RegisterType((*SyncReplicateRequest)(nil), "varlog.snpb.SyncReplicateRequest")
	proto.RegisterType((*SyncReplicateResponse)(nil), "varlog.snpb.SyncReplicateResponse")
}

func init() { proto.RegisterFile("replicator.proto", fileDescriptor_e741e2c5586b74b6) }

var fileDescriptor_e741e2c5586b74b6 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5f, 0x4f, 0x13, 0x4b,
	0x14, 0xef, 0x94, 0x2d, 0x5c, 0xa6, 0x2d, 0xb7, 0x0c, 0x97, 0x4b, 0x6f, 0x93, 0xdb, 0xad, 0xeb,
	0x4b, 0x63, 0xa4, 0x18, 0x88, 0x89, 0x7f, 0x1e, 0x8c, 0x85, 0x06, 0x49, 0x6a, 0x69, 0x66, 0x89,
	0x21, 0xbe, 0x34, 0xd3, 0xee, 0xb0, 0x6e, 0xd8, 0xee, 0xac, 0x33, 0xb3, 0x24, 0xbc, 0x18, 0xdf,
	0x34, 0x7c, 0x07, 0x12, 0x12, 0x79, 0xf0, 0xd1, 0xef, 0xe0, 0x0b, 0xbe, 0xf9, 0x09, 0x9a, 0x58,
	0x1f, 0xf4, 0x33, 0xf0, 0x64, 0x3a, 0xed, 0xae, 0x94, 0xaa, 0xc1, 0x4a, 0x78, 0xea, 0x39, 0x9d,
	0xdf, 0xfc, 0xce, 0x39, 0xbf, 0x73, 0xce, 0x0e, 0xcc, 0x70, 0xea, 0xbb, 0x4e, 0x8b, 0x48, 0xc6,
	0x4b, 0x3e, 0x67, 0x92, 0xa1, 0xe4, 0x1e, 0xe1, 0x2e, 0xb3, 0x4b, 0xc2, 0xf3, 0x9b, 0xb9, 0x45,
	0xdb, 0x91, 0xcf, 0x82, 0x66, 0xa9, 0xc5, 0xda, 0x4b, 0x36, 0xb3, 0xd9, 0x92, 0xc2, 0x34, 0x83,
	0x1d, 0xe5, 0x29, 0x47, 0x59, 0xfd, 0xbb, 0xc6, 0xcb, 0x38, 0x44, 0x78, 0x40, 0xe8, 0x30, 0x0f,
	0xd3, 0xe7, 0x01, 0x15, 0x12, 0xed, 0xc1, 0xb4, 0xcb, 0xec, 0x86, 0x90, 0x9c, 0x92, 0x76, 0xc3,
	0xb1, 0xb2, 0xa0, 0x00, 0x8a, 0xe9, 0x32, 0xee, 0x76, 0xf4, 0x64, 0x95, 0xd9, 0xa6, 0xfa, 0x7f,
	0x63, 0xed, 0xb4, 0xa3, 0x3f, 0x18, 0xc4, 0xb3, 0x48, 0xd0, 0xde, 0x25, 0xbb, 0x84, 0xa9, 0xc8,
	0xfd, 0x8c, 0xc2, 0x1f, 0x7f, 0x37, 0x32, 0xe5, 0xbe, 0x4f, 0x45, 0xe9, 0x0c, 0x05, 0x4e, 0xba,
	0x91, 0x63, 0xa1, 0x6d, 0xa8, 0xb9, 0xae, 0xf0, 0xb2, 0xf1, 0x02, 0x28, 0x6a, 0xe5, 0xb5, 0x6e,
	0x47, 0xd7, 0xaa, 0x55, 0xb3, 0x76, 0xda, 0xd1, 0xef, 0x8c, 0x15, 0xa7, 0x6a, 0xd6, 0xb0, 0x62,
	0x44, 0x59, 0x38, 0xe5, 0x93, 0x7d, 0x97, 0x11, 0x2b, 0x3b, 0x51, 0x00, 0xc5, 0x14, 0x0e, 0x5d,
	0xe3, 0x4b, 0x1c, 0xce, 0x0d, 0x49, 0x20, 0x7c, 0xe6, 0x09, 0x8a, 0x5e, 0xc0, 0xbf, 0x85, 0x64,
	0x9c, 0xd8, 0xb4, 0xe1, 0x31, 0x8b, 0x7e, 0x57, 0xe1, 0x49, 0xb7, 0xa3, 0xa7, 0xcd, 0xfe, 0x51,
	0x8d, 0x59, 0x54, 0xe9, 0xf0, 0x70, 0x9c, 0xfc, 0x86, 0x48, 0x70, 0x5a, 0x9c, 0x71, 0xad, 0xd1,
	0x1e, 0xc4, 0xaf, 0xb6, 0x07, 0x13, 0x97, 0xdd, 0x03, 0xe3, 0x04, 0xc0, 0x94, 0xb9, 0xef, 0xb5,
	0xea, 0x4c, 0x38, 0x3d, 0xa9, 0xa3, 0x50, 0xe0, 0xd2, 0xdb, 0xbd, 0x0d, 0x35, 0xfb, 0xdc, 0x20,
	0xad, 0xff, 0x01, 0xf3, 0xba, 0x62, 0xee, 0x31, 0xde, 0xd3, 0xbe, 0x1e, 0xe9, 0xc0, 0xf8, 0x04,
	0x20, 0xec, 0x95, 0x62, 0x4a, 0x22, 0x03, 0x81, 0x6e, 0xc2, 0x84, 0x90, 0x44, 0x52, 0x55, 0xc9,
	0xcc, 0xf2, 0xbf, 0xa5, 0x33, 0x2b, 0x59, 0x0a, 0x71, 0x14, 0xf7, 0x41, 0xe8, 0x36, 0x4c, 0xec,
	0x38, 0x5c, 0x48, 0x95, 0x5d, 0x72, 0xf9, 0xbf, 0x11, 0x74, 0x28, 0x50, 0x59, 0x3b, 0xe9, 0xe8,
	0x31, 0xdc, 0x47, 0xa3, 0x15, 0xa8, 0xb9, 0x44, 0x48, 0xd5, 0x98, 0x0b, 0xdc, 0x52, 0x60, 0x74,
	0x17, 0x4e, 0xb5, 0x02, 0xce, 0xa9, 0x27, 0xb3, 0xda, 0xc5, 0xee, 0x85, 0x78, 0xe3, 0x43, 0x1c,
	0xfe, 0xd3, 0x3b, 0x0f, 0x97, 0x83, 0x86, 0x5f, 0x87, 0x28, 0x7f, 0x30, 0x56, 0xfe, 0xf1, 0x31,
	0xf3, 0x9f, 0xf8, 0xbd, 0xfc, 0x11, 0x82, 0x9a, 0x45, 0x24, 0x51, 0x75, 0xa7, 0xb0, 0xb2, 0x47,
	0x97, 0x2a, 0x71, 0x25, 0x4b, 0x65, 0x3c, 0x82, 0xf3, 0xe7, 0xa4, 0x1c, 0x7c, 0x65, 0x96, 0xe0,
	0xa4, 0x50, 0x33, 0x34, 0x10, 0x73, 0xe1, 0x87, 0xa3, 0x13, 0x08, 0x3c, 0x80, 0xdd, 0x78, 0x05,
	0xe0, 0x74, 0x34, 0x51, 0xe8, 0x7f, 0x98, 0xa8, 0x60, 0xbc, 0x89, 0x33, 0xb1, 0x1c, 0x3a, 0x38,
	0x2c, 0xcc, 0x44, 0x27, 0x15, 0xce, 0x19, 0x47, 0x45, 0x98, 0xdc, 0xa8, 0x35, 0xea, 0x78, 0x73,
	0x1d, 0x57, 0x4c, 0x33, 0x03, 0x72, 0x0b, 0x07, 0x87, 0x85, 0xb9, 0x08, 0xb4, 0xe1, 0xd5, 0x39,
	0xb3, 0x39, 0x15, 0x02, 0x5d, 0x87, 0x7f, 0xad, 0x6e, 0x3e, 0xae, 0x57, 0x2b, 0x5b, 0x95, 0x4c,
	0x3c, 0x37, 0x7f, 0x70, 0x58, 0x98, 0x8d, 0x60, 0xab, 0xac, 0xed, 0xbb, 0x54, 0xd2, 0x5c, 0xea,
	0xf5, 0x9b, 0x7c, 0xec, 0xed, 0x71, 0x3e, 0xf6, 0xee, 0x38, 0x0f, 0x96, 0xdf, 0x03, 0x38, 0x8b,
	0xa3, 0xc7, 0xc8, 0xa4, 0x7c, 0xcf, 0x69, 0x51, 0xb4, 0x05, 0xa7, 0xa3, 0x2a, 0x91, 0x3e, 0x54,
	0xcd, 0xe8, 0x43, 0x93, 0x2b, 0xfc, 0x1c, 0xd0, 0x17, 0xc8, 0x88, 0x15, 0xc1, 0x2d, 0x80, 0xb6,
	0x61, 0x7a, 0x48, 0x3f, 0x74, 0x6d, 0x44, 0xa7, 0xf3, 0x63, 0x9a, 0x33, 0x7e, 0x05, 0x09, 0xd9,
	0xcb, 0xf7, 0x4f, 0xba, 0x79, 0xf0, 0xb1, 0x9b, 0x07, 0x47, 0x9f, 0xf3, 0xe0, 0xe9, 0xe2, 0x45,
	0xba, 0xae, 0x1e, 0xd1, 0x1e, 0x69, 0x73, 0x52, 0xd9, 0x2b, 0xdf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x19, 0x23, 0x28, 0xe3, 0x95, 0x07, 0x00, 0x00,
}

func (x SyncState) String() string {
	s, ok := SyncState_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *SyncPosition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SyncPosition)
	if !ok {
		that2, ok := that.(SyncPosition)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LLSN != that1.LLSN {
		return false
	}
	if this.GLSN != that1.GLSN {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReplicatorServiceClient is the client API for ReplicatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicatorServiceClient interface {
	Replicate(ctx context.Context, opts ...grpc.CallOption) (ReplicatorService_ReplicateClient, error)
	SyncReplicate(ctx context.Context, in *SyncReplicateRequest, opts ...grpc.CallOption) (*SyncReplicateResponse, error)
}

type replicatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewReplicatorServiceClient(cc *grpc.ClientConn) ReplicatorServiceClient {
	return &replicatorServiceClient{cc}
}

func (c *replicatorServiceClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (ReplicatorService_ReplicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReplicatorService_serviceDesc.Streams[0], "/varlog.snpb.ReplicatorService/Replicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicatorServiceReplicateClient{stream}
	return x, nil
}

type ReplicatorService_ReplicateClient interface {
	Send(*ReplicationRequest) error
	Recv() (*ReplicationResponse, error)
	grpc.ClientStream
}

type replicatorServiceReplicateClient struct {
	grpc.ClientStream
}

func (x *replicatorServiceReplicateClient) Send(m *ReplicationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicatorServiceReplicateClient) Recv() (*ReplicationResponse, error) {
	m := new(ReplicationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicatorServiceClient) SyncReplicate(ctx context.Context, in *SyncReplicateRequest, opts ...grpc.CallOption) (*SyncReplicateResponse, error) {
	out := new(SyncReplicateResponse)
	err := c.cc.Invoke(ctx, "/varlog.snpb.ReplicatorService/SyncReplicate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicatorServiceServer is the server API for ReplicatorService service.
type ReplicatorServiceServer interface {
	Replicate(ReplicatorService_ReplicateServer) error
	SyncReplicate(context.Context, *SyncReplicateRequest) (*SyncReplicateResponse, error)
}

// UnimplementedReplicatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReplicatorServiceServer struct {
}

func (*UnimplementedReplicatorServiceServer) Replicate(srv ReplicatorService_ReplicateServer) error {
	return status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (*UnimplementedReplicatorServiceServer) SyncReplicate(ctx context.Context, req *SyncReplicateRequest) (*SyncReplicateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncReplicate not implemented")
}

func RegisterReplicatorServiceServer(s *grpc.Server, srv ReplicatorServiceServer) {
	s.RegisterService(&_ReplicatorService_serviceDesc, srv)
}

func _ReplicatorService_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicatorServiceServer).Replicate(&replicatorServiceReplicateServer{stream})
}

type ReplicatorService_ReplicateServer interface {
	Send(*ReplicationResponse) error
	Recv() (*ReplicationRequest, error)
	grpc.ServerStream
}

type replicatorServiceReplicateServer struct {
	grpc.ServerStream
}

func (x *replicatorServiceReplicateServer) Send(m *ReplicationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicatorServiceReplicateServer) Recv() (*ReplicationRequest, error) {
	m := new(ReplicationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ReplicatorService_SyncReplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServiceServer).SyncReplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/varlog.snpb.ReplicatorService/SyncReplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServiceServer).SyncReplicate(ctx, req.(*SyncReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReplicatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "varlog.snpb.ReplicatorService",
	HandlerType: (*ReplicatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncReplicate",
			Handler:    _ReplicatorService_SyncReplicate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _ReplicatorService_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "replicator.proto",
}

func (m *ReplicationRequest) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintReplicator(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LLSN))
		i--
		dAtA[i] = 0x10
	}
	if m.LogStreamID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LogStreamID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.LLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LLSN))
		i--
		dAtA[i] = 0x18
	}
	if m.LogStreamID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LogStreamID))
		i--
		dAtA[i] = 0x10
	}
	if m.StorageNodeID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.StorageNodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncPosition) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.GLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.GLSN))
		i--
		dAtA[i] = 0x10
	}
	if m.LLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LLSN))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncStatus) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	{
		size, err := m.Current.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Last.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.First.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.State != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncReplicateRequest) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncReplicateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncReplicateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.LogStreamID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LogStreamID))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintReplicator(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Current.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Last.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.First.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *SyncReplicateResponse) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncReplicateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncReplicateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReplicator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintReplicator(dAtA []byte, offset int, v uint64) int {
	offset -= sovReplicator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReplicationRequest) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LogStreamID != 0 {
		n += 1 + sovReplicator(uint64(m.LogStreamID))
	}
	if m.LLSN != 0 {
		n += 1 + sovReplicator(uint64(m.LLSN))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovReplicator(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReplicationResponse) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StorageNodeID != 0 {
		n += 1 + sovReplicator(uint64(m.StorageNodeID))
	}
	if m.LogStreamID != 0 {
		n += 1 + sovReplicator(uint64(m.LogStreamID))
	}
	if m.LLSN != 0 {
		n += 1 + sovReplicator(uint64(m.LLSN))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncPosition) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LLSN != 0 {
		n += 1 + sovReplicator(uint64(m.LLSN))
	}
	if m.GLSN != 0 {
		n += 1 + sovReplicator(uint64(m.GLSN))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncStatus) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovReplicator(uint64(m.State))
	}
	l = m.First.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Last.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Current.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncReplicateRequest) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.First.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Last.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Current.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovReplicator(uint64(l))
	}
	if m.LogStreamID != 0 {
		n += 1 + sovReplicator(uint64(m.LogStreamID))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncReplicateResponse) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.ProtoSize()
		n += 1 + l + sovReplicator(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovReplicator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReplicator(x uint64) (n int) {
	return sovReplicator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReplicationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogStreamID", wireType)
			}
			m.LogStreamID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogStreamID |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LLSN", wireType)
			}
			m.LLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LLSN |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageNodeID", wireType)
			}
			m.StorageNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageNodeID |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.StorageNodeID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogStreamID", wireType)
			}
			m.LogStreamID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogStreamID |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LLSN", wireType)
			}
			m.LLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LLSN |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LLSN", wireType)
			}
			m.LLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LLSN |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.LLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GLSN", wireType)
			}
			m.GLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GLSN |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.GLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= SyncState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.First.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Last", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Last.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Current", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Current.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncReplicateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncReplicateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncReplicateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.First.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Last", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Last.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Current", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Current.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogStreamID", wireType)
			}
			m.LogStreamID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogStreamID |= github_daumkakao_com_varlog_varlog_pkg_varlog_types.LogStreamID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncReplicateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncReplicateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncReplicateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &SyncStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReplicator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReplicator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReplicator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReplicator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReplicator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReplicator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReplicator = fmt.Errorf("proto: unexpected end of group")
)
