// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/snpb/replicator.proto

package snpb

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	strconv "strconv"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"

	github_com_kakao_varlog_pkg_types "github.com/kakao/varlog/pkg/types"
	varlogpb "github.com/kakao/varlog/proto/varlogpb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SyncState int32

const (
	SyncStateError      SyncState = 0
	SyncStateInProgress SyncState = 1
	SyncStateComplete   SyncState = 2
)

var SyncState_name = map[int32]string{
	0: "ERROR",
	1: "IN_PROGRESS",
	2: "COMPLETE",
}

var SyncState_value = map[string]int32{
	"ERROR":       0,
	"IN_PROGRESS": 1,
	"COMPLETE":    2,
}

func (SyncState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{0}
}

// ReplicationRequest contains LLSN (Local Log Sequence Number) that indicates
// a log position in the local log stream of the primary storage node.
type ReplicationRequest struct {
	LogStreamID          github_com_kakao_varlog_pkg_types.LogStreamID `protobuf:"varint,1,opt,name=log_stream_id,json=logStreamId,proto3,casttype=github.com/kakao/varlog/pkg/types.LogStreamID" json:"log_stream_id,omitempty"`
	LLSN                 github_com_kakao_varlog_pkg_types.LLSN        `protobuf:"varint,2,opt,name=llsn,proto3,casttype=github.com/kakao/varlog/pkg/types.LLSN" json:"llsn,omitempty"`
	Payload              []byte                                                   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *ReplicationRequest) Reset()         { *m = ReplicationRequest{} }
func (m *ReplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicationRequest) ProtoMessage()    {}
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{0}
}
func (m *ReplicationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReplicationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationRequest.Merge(m, src)
}
func (m *ReplicationRequest) XXX_Size() int {
	return m.ProtoSize()
}
func (m *ReplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationRequest proto.InternalMessageInfo

func (m *ReplicationRequest) GetLogStreamID() github_com_kakao_varlog_pkg_types.LogStreamID {
	if m != nil {
		return m.LogStreamID
	}
	return 0
}

func (m *ReplicationRequest) GetLLSN() github_com_kakao_varlog_pkg_types.LLSN {
	if m != nil {
		return m.LLSN
	}
	return 0
}

func (m *ReplicationRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// ReplicationResponse indicates that a log entry at given LLSN is replicated.
type ReplicationResponse struct {
	StorageNodeID        github_com_kakao_varlog_pkg_types.StorageNodeID `protobuf:"varint,1,opt,name=storage_node_id,json=storageNodeId,proto3,casttype=github.com/kakao/varlog/pkg/types.StorageNodeID" json:"storage_node_id,omitempty"`
	LogStreamID          github_com_kakao_varlog_pkg_types.LogStreamID   `protobuf:"varint,2,opt,name=log_stream_id,json=logStreamId,proto3,casttype=github.com/kakao/varlog/pkg/types.LogStreamID" json:"log_stream_id,omitempty"`
	LLSN                 github_com_kakao_varlog_pkg_types.LLSN          `protobuf:"varint,3,opt,name=llsn,proto3,casttype=github.com/kakao/varlog/pkg/types.LLSN" json:"llsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *ReplicationResponse) Reset()         { *m = ReplicationResponse{} }
func (m *ReplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicationResponse) ProtoMessage()    {}
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{1}
}
func (m *ReplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationResponse.Merge(m, src)
}
func (m *ReplicationResponse) XXX_Size() int {
	return m.ProtoSize()
}
func (m *ReplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationResponse proto.InternalMessageInfo

func (m *ReplicationResponse) GetStorageNodeID() github_com_kakao_varlog_pkg_types.StorageNodeID {
	if m != nil {
		return m.StorageNodeID
	}
	return 0
}

func (m *ReplicationResponse) GetLogStreamID() github_com_kakao_varlog_pkg_types.LogStreamID {
	if m != nil {
		return m.LogStreamID
	}
	return 0
}

func (m *ReplicationResponse) GetLLSN() github_com_kakao_varlog_pkg_types.LLSN {
	if m != nil {
		return m.LLSN
	}
	return 0
}

type SyncPosition struct {
	LLSN                 github_com_kakao_varlog_pkg_types.LLSN `protobuf:"varint,1,opt,name=llsn,proto3,casttype=github.com/kakao/varlog/pkg/types.LLSN" json:"llsn,omitempty"`
	GLSN                 github_com_kakao_varlog_pkg_types.GLSN `protobuf:"varint,2,opt,name=glsn,proto3,casttype=github.com/kakao/varlog/pkg/types.GLSN" json:"glsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *SyncPosition) Reset()         { *m = SyncPosition{} }
func (m *SyncPosition) String() string { return proto.CompactTextString(m) }
func (*SyncPosition) ProtoMessage()    {}
func (*SyncPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{2}
}
func (m *SyncPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPosition.Merge(m, src)
}
func (m *SyncPosition) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPosition.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPosition proto.InternalMessageInfo

func (m *SyncPosition) GetLLSN() github_com_kakao_varlog_pkg_types.LLSN {
	if m != nil {
		return m.LLSN
	}
	return 0
}

func (m *SyncPosition) GetGLSN() github_com_kakao_varlog_pkg_types.GLSN {
	if m != nil {
		return m.GLSN
	}
	return 0
}

type SyncStatus struct {
	State                SyncState    `protobuf:"varint,1,opt,name=state,proto3,enum=varlog.snpb.SyncState" json:"state,omitempty"`
	First                SyncPosition `protobuf:"bytes,2,opt,name=first,proto3" json:"first"`
	Last                 SyncPosition `protobuf:"bytes,3,opt,name=last,proto3" json:"last"`
	Current              SyncPosition `protobuf:"bytes,4,opt,name=current,proto3" json:"current"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncStatus) Reset()         { *m = SyncStatus{} }
func (m *SyncStatus) String() string { return proto.CompactTextString(m) }
func (*SyncStatus) ProtoMessage()    {}
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{3}
}
func (m *SyncStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncStatus.Merge(m, src)
}
func (m *SyncStatus) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SyncStatus proto.InternalMessageInfo

func (m *SyncStatus) GetState() SyncState {
	if m != nil {
		return m.State
	}
	return SyncStateError
}

func (m *SyncStatus) GetFirst() SyncPosition {
	if m != nil {
		return m.First
	}
	return SyncPosition{}
}

func (m *SyncStatus) GetLast() SyncPosition {
	if m != nil {
		return m.Last
	}
	return SyncPosition{}
}

func (m *SyncStatus) GetCurrent() SyncPosition {
	if m != nil {
		return m.Current
	}
	return SyncPosition{}
}

type SyncPayload struct {
	CommitContext        *varlogpb.CommitContext `protobuf:"bytes,1,opt,name=commit_context,json=commitContext,proto3" json:"commit_context,omitempty"`
	LogEntry             *varlogpb.LogEntry      `protobuf:"bytes,2,opt,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SyncPayload) Reset()         { *m = SyncPayload{} }
func (m *SyncPayload) String() string { return proto.CompactTextString(m) }
func (*SyncPayload) ProtoMessage()    {}
func (*SyncPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{4}
}
func (m *SyncPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncPayload.Merge(m, src)
}
func (m *SyncPayload) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SyncPayload proto.InternalMessageInfo

func (m *SyncPayload) GetCommitContext() *varlogpb.CommitContext {
	if m != nil {
		return m.CommitContext
	}
	return nil
}

func (m *SyncPayload) GetLogEntry() *varlogpb.LogEntry {
	if m != nil {
		return m.LogEntry
	}
	return nil
}

type SyncInitRequest struct {
	ClusterID            github_com_kakao_varlog_pkg_types.ClusterID `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3,casttype=github.com/kakao/varlog/pkg/types.ClusterID" json:"cluster_id,omitempty"`
	Source               Replica                                                `protobuf:"bytes,2,opt,name=source,proto3" json:"source"`
	Destination          Replica                                                `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination"`
	First                SyncPosition                                           `protobuf:"bytes,4,opt,name=first,proto3" json:"first"`
	Last                 SyncPosition                                           `protobuf:"bytes,5,opt,name=last,proto3" json:"last"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *SyncInitRequest) Reset()         { *m = SyncInitRequest{} }
func (m *SyncInitRequest) String() string { return proto.CompactTextString(m) }
func (*SyncInitRequest) ProtoMessage()    {}
func (*SyncInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{5}
}
func (m *SyncInitRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncInitRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInitRequest.Merge(m, src)
}
func (m *SyncInitRequest) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInitRequest proto.InternalMessageInfo

func (m *SyncInitRequest) GetClusterID() github_com_kakao_varlog_pkg_types.ClusterID {
	if m != nil {
		return m.ClusterID
	}
	return 0
}

func (m *SyncInitRequest) GetSource() Replica {
	if m != nil {
		return m.Source
	}
	return Replica{}
}

func (m *SyncInitRequest) GetDestination() Replica {
	if m != nil {
		return m.Destination
	}
	return Replica{}
}

func (m *SyncInitRequest) GetFirst() SyncPosition {
	if m != nil {
		return m.First
	}
	return SyncPosition{}
}

func (m *SyncInitRequest) GetLast() SyncPosition {
	if m != nil {
		return m.Last
	}
	return SyncPosition{}
}

type SyncInitResponse struct {
	First                SyncPosition `protobuf:"bytes,1,opt,name=first,proto3" json:"first"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SyncInitResponse) Reset()         { *m = SyncInitResponse{} }
func (m *SyncInitResponse) String() string { return proto.CompactTextString(m) }
func (*SyncInitResponse) ProtoMessage()    {}
func (*SyncInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{6}
}
func (m *SyncInitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncInitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInitResponse.Merge(m, src)
}
func (m *SyncInitResponse) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInitResponse proto.InternalMessageInfo

func (m *SyncInitResponse) GetFirst() SyncPosition {
	if m != nil {
		return m.First
	}
	return SyncPosition{}
}

type SyncReplicateRequest struct {
	ClusterID            github_com_kakao_varlog_pkg_types.ClusterID `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3,casttype=github.com/kakao/varlog/pkg/types.ClusterID" json:"cluster_id,omitempty"`
	Source               Replica                                                `protobuf:"bytes,2,opt,name=source,proto3" json:"source"`
	Destination          Replica                                                `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination"`
	Payload              SyncPayload                                            `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *SyncReplicateRequest) Reset()         { *m = SyncReplicateRequest{} }
func (m *SyncReplicateRequest) String() string { return proto.CompactTextString(m) }
func (*SyncReplicateRequest) ProtoMessage()    {}
func (*SyncReplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{7}
}
func (m *SyncReplicateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncReplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncReplicateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncReplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReplicateRequest.Merge(m, src)
}
func (m *SyncReplicateRequest) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncReplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReplicateRequest proto.InternalMessageInfo

func (m *SyncReplicateRequest) GetClusterID() github_com_kakao_varlog_pkg_types.ClusterID {
	if m != nil {
		return m.ClusterID
	}
	return 0
}

func (m *SyncReplicateRequest) GetSource() Replica {
	if m != nil {
		return m.Source
	}
	return Replica{}
}

func (m *SyncReplicateRequest) GetDestination() Replica {
	if m != nil {
		return m.Destination
	}
	return Replica{}
}

func (m *SyncReplicateRequest) GetPayload() SyncPayload {
	if m != nil {
		return m.Payload
	}
	return SyncPayload{}
}

type SyncReplicateResponse struct {
	Status               *SyncStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SyncReplicateResponse) Reset()         { *m = SyncReplicateResponse{} }
func (m *SyncReplicateResponse) String() string { return proto.CompactTextString(m) }
func (*SyncReplicateResponse) ProtoMessage()    {}
func (*SyncReplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85705cb817486b63, []int{8}
}
func (m *SyncReplicateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncReplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncReplicateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SyncReplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncReplicateResponse.Merge(m, src)
}
func (m *SyncReplicateResponse) XXX_Size() int {
	return m.ProtoSize()
}
func (m *SyncReplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncReplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncReplicateResponse proto.InternalMessageInfo

func (m *SyncReplicateResponse) GetStatus() *SyncStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("varlog.snpb.SyncState", SyncState_name, SyncState_value)
	proto.RegisterType((*ReplicationRequest)(nil), "varlog.snpb.ReplicationRequest")
	proto.RegisterType((*ReplicationResponse)(nil), "varlog.snpb.ReplicationResponse")
	proto.RegisterType((*SyncPosition)(nil), "varlog.snpb.SyncPosition")
	proto.RegisterType((*SyncStatus)(nil), "varlog.snpb.SyncStatus")
	proto.RegisterType((*SyncPayload)(nil), "varlog.snpb.SyncPayload")
	proto.RegisterType((*SyncInitRequest)(nil), "varlog.snpb.SyncInitRequest")
	proto.RegisterType((*SyncInitResponse)(nil), "varlog.snpb.SyncInitResponse")
	proto.RegisterType((*SyncReplicateRequest)(nil), "varlog.snpb.SyncReplicateRequest")
	proto.RegisterType((*SyncReplicateResponse)(nil), "varlog.snpb.SyncReplicateResponse")
}

func init() { proto.RegisterFile("proto/snpb/replicator.proto", fileDescriptor_85705cb817486b63) }

var fileDescriptor_85705cb817486b63 = []byte{
	// 888 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xf7, 0xb8, 0x9b, 0x34, 0x7e, 0x8e, 0xd3, 0x30, 0x6d, 0x89, 0x59, 0xa8, 0xd7, 0x2c, 0x17,
	0x0b, 0x51, 0x1b, 0x5c, 0x51, 0x95, 0x00, 0x97, 0x18, 0x2b, 0x58, 0x98, 0x24, 0x1d, 0xf7, 0x80,
	0xb8, 0x58, 0xeb, 0xdd, 0xc9, 0xb2, 0xca, 0x7a, 0x67, 0x99, 0x99, 0x05, 0xf2, 0x17, 0x14, 0xe5,
	0xc8, 0x3d, 0x52, 0x25, 0x7a, 0x40, 0x9c, 0x38, 0xf3, 0x17, 0xe4, 0x88, 0xb8, 0x70, 0xb3, 0x84,
	0xb9, 0x70, 0xe6, 0xd8, 0x13, 0xda, 0xd9, 0x0f, 0x3b, 0x71, 0x5b, 0xc5, 0x55, 0xc5, 0x81, 0xd3,
	0xce, 0xcc, 0xfb, 0xbd, 0x8f, 0xf9, 0xbd, 0x8f, 0x1d, 0x78, 0x3d, 0xe4, 0x4c, 0xb2, 0x96, 0x08,
	0xc2, 0x51, 0x8b, 0xd3, 0xd0, 0xf7, 0x6c, 0x4b, 0x32, 0xde, 0x54, 0xa7, 0xb8, 0xfc, 0x8d, 0xc5,
	0x7d, 0xe6, 0x36, 0x63, 0xa9, 0x7e, 0xdb, 0xf5, 0xe4, 0x57, 0xd1, 0xa8, 0x69, 0xb3, 0x71, 0xcb,
	0x65, 0x2e, 0x6b, 0x29, 0xcc, 0x28, 0x3a, 0x54, 0xbb, 0xc4, 0x4c, 0xbc, 0x4a, 0x74, 0xf5, 0xad,
	0x44, 0x37, 0x1c, 0xb5, 0xc6, 0x54, 0x5a, 0x8e, 0x25, 0xad, 0x54, 0x80, 0xe7, 0x7d, 0x25, 0x67,
	0xe6, 0x3f, 0x08, 0x30, 0x49, 0xbd, 0x7b, 0x2c, 0x20, 0xf4, 0xeb, 0x88, 0x0a, 0x89, 0x19, 0x54,
	0x7c, 0xe6, 0x0e, 0x85, 0xe4, 0xd4, 0x1a, 0x0f, 0x3d, 0xa7, 0x8a, 0xea, 0xa8, 0x51, 0xd9, 0xf9,
	0x6c, 0x3a, 0x31, 0xca, 0x7d, 0xe6, 0x0e, 0xd4, 0x79, 0xef, 0x93, 0x27, 0x13, 0xe3, 0x5e, 0x1a,
	0x9c, 0x63, 0x45, 0xe3, 0x23, 0xeb, 0xc8, 0x62, 0x2a, 0xcc, 0x24, 0x84, 0xec, 0x13, 0x1e, 0xb9,
	0x2d, 0x79, 0x1c, 0x52, 0xd1, 0x9c, 0xd3, 0x25, 0x65, 0x3f, 0xdf, 0x38, 0xf8, 0x3e, 0x68, 0xbe,
	0x2f, 0x82, 0x6a, 0xb1, 0x8e, 0x1a, 0xda, 0xce, 0xc7, 0xd3, 0x89, 0xa1, 0xf5, 0xfb, 0x83, 0xbd,
	0x27, 0x13, 0xe3, 0xbd, 0xe5, 0x1c, 0xf4, 0x07, 0x7b, 0x44, 0x99, 0xc2, 0x55, 0xb8, 0x1a, 0x5a,
	0xc7, 0x3e, 0xb3, 0x9c, 0xea, 0x95, 0x3a, 0x6a, 0xac, 0x93, 0x6c, 0x6b, 0xfe, 0x5e, 0x84, 0xeb,
	0xe7, 0x2e, 0x2d, 0x42, 0x16, 0x08, 0x8a, 0xbf, 0x85, 0x6b, 0x42, 0x32, 0x6e, 0xb9, 0x74, 0x18,
	0x30, 0x87, 0xce, 0xee, 0xbd, 0x3f, 0x9d, 0x18, 0x95, 0x41, 0x22, 0xda, 0x63, 0x0e, 0x55, 0x37,
	0xdf, 0x5e, 0x2a, 0xb0, 0x73, 0xda, 0xa4, 0x22, 0xe6, 0xb6, 0xce, 0x22, 0xdd, 0xc5, 0xff, 0x88,
	0xee, 0x2b, 0x2f, 0x8d, 0x6e, 0xf3, 0x57, 0x04, 0xeb, 0x83, 0xe3, 0xc0, 0x3e, 0x60, 0xc2, 0x8b,
	0x59, 0xcd, 0x7d, 0xa0, 0x97, 0x97, 0xd2, 0xfb, 0xa0, 0xb9, 0x17, 0xaa, 0x64, 0xf7, 0x45, 0x4c,
	0xee, 0x2a, 0x93, 0xb1, 0xa9, 0x6d, 0xed, 0xef, 0x47, 0x06, 0x32, 0xff, 0x44, 0x00, 0x71, 0xf0,
	0x03, 0x69, 0xc9, 0x48, 0xe0, 0x77, 0x60, 0x45, 0x48, 0x4b, 0x52, 0x15, 0xfb, 0x46, 0xfb, 0xd5,
	0xe6, 0x5c, 0x3b, 0x36, 0x33, 0x1c, 0x25, 0x09, 0x08, 0xbf, 0x0f, 0x2b, 0x87, 0x1e, 0x17, 0x52,
	0x85, 0x55, 0x6e, 0xbf, 0xb6, 0x80, 0xce, 0x28, 0xd9, 0xd1, 0xce, 0x26, 0x46, 0x81, 0x24, 0x68,
	0x7c, 0x07, 0x34, 0xdf, 0x12, 0x52, 0xe5, 0xe0, 0x12, 0x5a, 0x0a, 0x8c, 0x3f, 0x80, 0xab, 0x76,
	0xc4, 0x39, 0x0d, 0x64, 0x55, 0xbb, 0x9c, 0x5e, 0x86, 0x37, 0x7f, 0x40, 0x50, 0x56, 0xf2, 0xa4,
	0x0b, 0x70, 0x17, 0x36, 0x6c, 0x36, 0x1e, 0x7b, 0x72, 0x68, 0xb3, 0x40, 0xd2, 0xef, 0xa4, 0xba,
	0x6d, 0xb9, 0x5d, 0xcb, 0x2c, 0x66, 0x73, 0xa4, 0xd9, 0x51, 0xb0, 0x4e, 0x82, 0x22, 0x15, 0x7b,
	0x7e, 0x8b, 0xef, 0x42, 0x29, 0xae, 0x5d, 0x1a, 0x48, 0x7e, 0x7c, 0x91, 0x81, 0xdc, 0x42, 0x9f,
	0xb9, 0xdd, 0x18, 0x40, 0xd6, 0xfc, 0x74, 0xb5, 0xad, 0x9d, 0xc5, 0xc4, 0xff, 0x51, 0x84, 0x6b,
	0x71, 0x50, 0xbd, 0xc0, 0x93, 0xd9, 0xf0, 0x39, 0x04, 0xb0, 0xfd, 0x48, 0x48, 0xca, 0x67, 0x1d,
	0xb8, 0x3b, 0x9d, 0x18, 0xa5, 0x4e, 0x72, 0xaa, 0x1a, 0xe1, 0xee, 0x52, 0x09, 0xcf, 0x35, 0x49,
	0x29, 0x35, 0xdd, 0x73, 0x70, 0x1b, 0x56, 0x05, 0x8b, 0xb8, 0x4d, 0xd3, 0xb0, 0x6f, 0x9c, 0xa3,
	0x32, 0x1d, 0x10, 0x29, 0x8b, 0x29, 0x12, 0x7f, 0x04, 0x65, 0x87, 0x0a, 0xe9, 0x05, 0x6a, 0x72,
	0xa4, 0xb9, 0x7b, 0x9e, 0xe2, 0x3c, 0x7c, 0x56, 0x29, 0xda, 0x0b, 0x55, 0xca, 0xca, 0x12, 0x95,
	0x62, 0xf6, 0x60, 0x73, 0x46, 0x6c, 0x3a, 0xe0, 0x72, 0xff, 0x68, 0x19, 0xff, 0xe6, 0xcf, 0x45,
	0xb8, 0x11, 0x4b, 0xb3, 0x99, 0x49, 0xff, 0xff, 0x99, 0xba, 0x37, 0xfb, 0x79, 0x24, 0xb9, 0xaa,
	0x2e, 0x72, 0x95, 0xc8, 0xb3, 0x36, 0xcb, 0x7e, 0x2e, 0x9f, 0xc2, 0xcd, 0x0b, 0x5c, 0xa5, 0xe4,
	0xb7, 0x60, 0x55, 0xa8, 0xf1, 0x92, 0xb2, 0xbf, 0xf5, 0xd4, 0xa9, 0x12, 0x09, 0x92, 0xc2, 0xde,
	0x7e, 0x88, 0xa0, 0x94, 0x0f, 0x1b, 0x7c, 0x0b, 0x56, 0xba, 0x84, 0xec, 0x93, 0xcd, 0x82, 0x8e,
	0x4f, 0x4e, 0xeb, 0x1b, 0xb9, 0xa4, 0xcb, 0x39, 0xe3, 0xb8, 0x01, 0xe5, 0xde, 0xde, 0xf0, 0x80,
	0xec, 0xef, 0x92, 0xee, 0x60, 0xb0, 0x89, 0xf4, 0xad, 0x93, 0xd3, 0xfa, 0xf5, 0x1c, 0xd4, 0x0b,
	0x0e, 0x38, 0x73, 0x39, 0x15, 0x02, 0xbf, 0x05, 0x6b, 0x9d, 0xfd, 0xcf, 0x0f, 0xfa, 0xdd, 0x07,
	0xdd, 0xcd, 0xa2, 0x7e, 0xf3, 0xe4, 0xb4, 0xfe, 0x4a, 0x0e, 0xeb, 0xb0, 0x71, 0xe8, 0x53, 0x49,
	0xf5, 0xf5, 0xef, 0x7f, 0xac, 0x15, 0x7e, 0x7a, 0x5c, 0x2b, 0xfc, 0xf2, 0xb8, 0x86, 0xda, 0x0f,
	0x8b, 0x00, 0x24, 0x7f, 0xa3, 0xe0, 0x07, 0x50, 0xca, 0xaf, 0x87, 0x8d, 0xa7, 0x51, 0x3a, 0xf7,
	0x96, 0xd0, 0xeb, 0xcf, 0x06, 0x24, 0xcc, 0x98, 0x85, 0x06, 0x7a, 0x17, 0xe1, 0x1e, 0xac, 0x65,
	0x05, 0x8b, 0xdf, 0x58, 0xe0, 0x66, 0x6e, 0x40, 0xe8, 0xb7, 0x9e, 0x21, 0xcd, 0xcc, 0xe1, 0x2f,
	0xa0, 0x72, 0x2e, 0x07, 0xf8, 0xcd, 0x05, 0x8d, 0x8b, 0xb5, 0xac, 0x9b, 0xcf, 0x83, 0x64, 0x96,
	0x77, 0x3e, 0x3c, 0x9b, 0xd6, 0xd0, 0x6f, 0xd3, 0x1a, 0x7a, 0xf4, 0x57, 0x0d, 0x7d, 0x79, 0xfb,
	0x32, 0xa5, 0x9d, 0x3f, 0xf3, 0x46, 0xab, 0x6a, 0x7d, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x79, 0xe0, 0x24, 0x52, 0xfb, 0x09, 0x00, 0x00,
}

func (x SyncState) String() string {
	s, ok := SyncState_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *SyncPosition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SyncPosition)
	if !ok {
		that2, ok := that.(SyncPosition)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.LLSN != that1.LLSN {
		return false
	}
	if this.GLSN != that1.GLSN {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReplicatorClient is the client API for Replicator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicatorClient interface {
	Replicate(ctx context.Context, opts ...grpc.CallOption) (Replicator_ReplicateClient, error)
	SyncInit(ctx context.Context, in *SyncInitRequest, opts ...grpc.CallOption) (*SyncInitResponse, error)
	SyncReplicate(ctx context.Context, in *SyncReplicateRequest, opts ...grpc.CallOption) (*SyncReplicateResponse, error)
}

type replicatorClient struct {
	cc *grpc.ClientConn
}

func NewReplicatorClient(cc *grpc.ClientConn) ReplicatorClient {
	return &replicatorClient{cc}
}

func (c *replicatorClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (Replicator_ReplicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Replicator_serviceDesc.Streams[0], "/varlog.snpb.Replicator/Replicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicatorReplicateClient{stream}
	return x, nil
}

type Replicator_ReplicateClient interface {
	Send(*ReplicationRequest) error
	Recv() (*ReplicationResponse, error)
	grpc.ClientStream
}

type replicatorReplicateClient struct {
	grpc.ClientStream
}

func (x *replicatorReplicateClient) Send(m *ReplicationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicatorReplicateClient) Recv() (*ReplicationResponse, error) {
	m := new(ReplicationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *replicatorClient) SyncInit(ctx context.Context, in *SyncInitRequest, opts ...grpc.CallOption) (*SyncInitResponse, error) {
	out := new(SyncInitResponse)
	err := c.cc.Invoke(ctx, "/varlog.snpb.Replicator/SyncInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicatorClient) SyncReplicate(ctx context.Context, in *SyncReplicateRequest, opts ...grpc.CallOption) (*SyncReplicateResponse, error) {
	out := new(SyncReplicateResponse)
	err := c.cc.Invoke(ctx, "/varlog.snpb.Replicator/SyncReplicate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicatorServer is the server API for Replicator service.
type ReplicatorServer interface {
	Replicate(Replicator_ReplicateServer) error
	SyncInit(context.Context, *SyncInitRequest) (*SyncInitResponse, error)
	SyncReplicate(context.Context, *SyncReplicateRequest) (*SyncReplicateResponse, error)
}

// UnimplementedReplicatorServer can be embedded to have forward compatible implementations.
type UnimplementedReplicatorServer struct {
}

func (*UnimplementedReplicatorServer) Replicate(srv Replicator_ReplicateServer) error {
	return status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (*UnimplementedReplicatorServer) SyncInit(ctx context.Context, req *SyncInitRequest) (*SyncInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncInit not implemented")
}
func (*UnimplementedReplicatorServer) SyncReplicate(ctx context.Context, req *SyncReplicateRequest) (*SyncReplicateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncReplicate not implemented")
}

func RegisterReplicatorServer(s *grpc.Server, srv ReplicatorServer) {
	s.RegisterService(&_Replicator_serviceDesc, srv)
}

func _Replicator_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicatorServer).Replicate(&replicatorReplicateServer{stream})
}

type Replicator_ReplicateServer interface {
	Send(*ReplicationResponse) error
	Recv() (*ReplicationRequest, error)
	grpc.ServerStream
}

type replicatorReplicateServer struct {
	grpc.ServerStream
}

func (x *replicatorReplicateServer) Send(m *ReplicationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicatorReplicateServer) Recv() (*ReplicationRequest, error) {
	m := new(ReplicationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Replicator_SyncInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).SyncInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/varlog.snpb.Replicator/SyncInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).SyncInit(ctx, req.(*SyncInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replicator_SyncReplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicatorServer).SyncReplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/varlog.snpb.Replicator/SyncReplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicatorServer).SyncReplicate(ctx, req.(*SyncReplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Replicator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "varlog.snpb.Replicator",
	HandlerType: (*ReplicatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncInit",
			Handler:    _Replicator_SyncInit_Handler,
		},
		{
			MethodName: "SyncReplicate",
			Handler:    _Replicator_SyncReplicate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _Replicator_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/snpb/replicator.proto",
}

func (m *ReplicationRequest) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintReplicator(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x1a
	}
	if m.LLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LLSN))
		i--
		dAtA[i] = 0x10
	}
	if m.LogStreamID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LogStreamID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.LLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LLSN))
		i--
		dAtA[i] = 0x18
	}
	if m.LogStreamID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LogStreamID))
		i--
		dAtA[i] = 0x10
	}
	if m.StorageNodeID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.StorageNodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncPosition) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.GLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.GLSN))
		i--
		dAtA[i] = 0x10
	}
	if m.LLSN != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.LLSN))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncStatus) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	{
		size, err := m.Current.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Last.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.First.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.State != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncPayload) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.LogEntry != nil {
		{
			size, err := m.LogEntry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReplicator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.CommitContext != nil {
		{
			size, err := m.CommitContext.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReplicator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SyncInitRequest) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncInitRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncInitRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	{
		size, err := m.Last.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.First.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Destination.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Source.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ClusterID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.ClusterID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncInitResponse) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncInitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncInitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	{
		size, err := m.First.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *SyncReplicateRequest) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncReplicateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncReplicateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	{
		size, err := m.Payload.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Destination.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Source.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReplicator(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ClusterID != 0 {
		i = encodeVarintReplicator(dAtA, i, uint64(m.ClusterID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SyncReplicateResponse) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncReplicateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.ProtoSize()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncReplicateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintReplicator(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintReplicator(dAtA []byte, offset int, v uint64) int {
	offset -= sovReplicator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReplicationRequest) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LogStreamID != 0 {
		n += 1 + sovReplicator(uint64(m.LogStreamID))
	}
	if m.LLSN != 0 {
		n += 1 + sovReplicator(uint64(m.LLSN))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovReplicator(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReplicationResponse) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StorageNodeID != 0 {
		n += 1 + sovReplicator(uint64(m.StorageNodeID))
	}
	if m.LogStreamID != 0 {
		n += 1 + sovReplicator(uint64(m.LogStreamID))
	}
	if m.LLSN != 0 {
		n += 1 + sovReplicator(uint64(m.LLSN))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncPosition) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LLSN != 0 {
		n += 1 + sovReplicator(uint64(m.LLSN))
	}
	if m.GLSN != 0 {
		n += 1 + sovReplicator(uint64(m.GLSN))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncStatus) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.State != 0 {
		n += 1 + sovReplicator(uint64(m.State))
	}
	l = m.First.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Last.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Current.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncPayload) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommitContext != nil {
		l = m.CommitContext.ProtoSize()
		n += 1 + l + sovReplicator(uint64(l))
	}
	if m.LogEntry != nil {
		l = m.LogEntry.ProtoSize()
		n += 1 + l + sovReplicator(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncInitRequest) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterID != 0 {
		n += 1 + sovReplicator(uint64(m.ClusterID))
	}
	l = m.Source.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Destination.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.First.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Last.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncInitResponse) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.First.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncReplicateRequest) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClusterID != 0 {
		n += 1 + sovReplicator(uint64(m.ClusterID))
	}
	l = m.Source.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Destination.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	l = m.Payload.ProtoSize()
	n += 1 + l + sovReplicator(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SyncReplicateResponse) ProtoSize() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.ProtoSize()
		n += 1 + l + sovReplicator(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovReplicator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReplicator(x uint64) (n int) {
	return sovReplicator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *SyncPayload) GetValue() interface{} {
	if this.CommitContext != nil {
		return this.CommitContext
	}
	if this.LogEntry != nil {
		return this.LogEntry
	}
	return nil
}

func (this *SyncPayload) SetValue(value interface{}) bool {
	switch vt := value.(type) {
	case *varlogpb.CommitContext:
		this.CommitContext = vt
	case *varlogpb.LogEntry:
		this.LogEntry = vt
	default:
		return false
	}
	return true
}
func (m *ReplicationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogStreamID", wireType)
			}
			m.LogStreamID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogStreamID |= github_com_kakao_varlog_pkg_types.LogStreamID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LLSN", wireType)
			}
			m.LLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LLSN |= github_com_kakao_varlog_pkg_types.LLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageNodeID", wireType)
			}
			m.StorageNodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StorageNodeID |= github_com_kakao_varlog_pkg_types.StorageNodeID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogStreamID", wireType)
			}
			m.LogStreamID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogStreamID |= github_com_kakao_varlog_pkg_types.LogStreamID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LLSN", wireType)
			}
			m.LLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LLSN |= github_com_kakao_varlog_pkg_types.LLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LLSN", wireType)
			}
			m.LLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LLSN |= github_com_kakao_varlog_pkg_types.LLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GLSN", wireType)
			}
			m.GLSN = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GLSN |= github_com_kakao_varlog_pkg_types.GLSN(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= SyncState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.First.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Last", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Last.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Current", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Current.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitContext", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommitContext == nil {
				m.CommitContext = &varlogpb.CommitContext{}
			}
			if err := m.CommitContext.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogEntry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LogEntry == nil {
				m.LogEntry = &varlogpb.LogEntry{}
			}
			if err := m.LogEntry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncInitRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncInitRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncInitRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			m.ClusterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterID |= github_com_kakao_varlog_pkg_types.ClusterID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Destination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.First.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Last", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Last.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncInitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncInitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncInitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.First.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncReplicateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncReplicateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncReplicateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterID", wireType)
			}
			m.ClusterID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClusterID |= github_com_kakao_varlog_pkg_types.ClusterID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Destination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Payload.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncReplicateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncReplicateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncReplicateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReplicator
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReplicator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &SyncStatus{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReplicator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReplicator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReplicator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReplicator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReplicator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReplicator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReplicator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReplicator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReplicator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReplicator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReplicator = fmt.Errorf("proto: unexpected end of group")
)
