apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - varlogmr.yaml
  - varlogmr-clear.yaml
  - varlogsn.yaml
  - varlogadm.yaml
  - ingress-nginx-configmap.yaml
  - varlogmr-vip-service.yaml
  - varlogadm-vip-service.yaml

configMapGenerator:
  - literals:
      - cluster_id="1"
      - replication_factor="3"
    name: varlog-conf
    namespace: default
    options:
      disableNameSuffixHash: true
