apiVersion: v1
kind: Service
metadata:
  name: varlogadm-rpc-vip
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  ports:
    - name: varlogadm-rpc
      port: 9093
