kind: Service
apiVersion: v1
metadata:
  name: varlogmr-rpc
  namespace: default
spec:
  selector:
    app: varlogmr
  ports:
    - name: rpc
      port: 9092
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: varlogmr
  namespace: default
  labels:
    app: varlogmr
    name: varlogmr
spec:
  selector:
    matchLabels:
      name: varlogmr
  template:
    metadata:
      labels:
        app: varlogmr
        name: varlogmr
    spec:
      volumes:
        - name: varlogmr-home
          hostPath:
            path: /varlog/mr
            type: DirectoryOrCreate
      initContainers:
        - name: volume-perm
          image: mdock.daumkakao.io/busybox:stable
          command:
            - "sh"
            - "-c"
            - "chmod -R 777 /varlog/mr"
          volumeMounts:
            - name: varlogmr-home
              mountPath: /varlog/mr
      containers:
        - name: varlogmr
          image: idock.daumkakao.io/varlog/all-in-one:latest
          command:
            - "python3"
            - "/varlog/bin/vmr.py"
          ports:
            - name: rpc
              containerPort: 9092
          env:
            - name: TZ
              value: Asia/Seoul
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: cluster_id
                  name: varlog-conf
            - name: REP_FACTOR
              valueFrom:
                configMapKeyRef:
                  key: replication_factor
                  name: varlog-conf
            - name: VMS_ADDRESS
              value: "$(VARLOGADM_RPC_SERVICE_HOST):$(VARLOGADM_RPC_SERVICE_PORT)"
            - name: VMR_HOME
              value: /varlog/mr
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: varlogmr-home
              mountPath: /varlog/mr
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "/varlog/tools/grpc_health_probe -addr=${HOST_IP}:9092"
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "/varlog/tools/grpc_health_probe -addr=${HOST_IP}:9092"
            periodSeconds: 10
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: varlog-type
                    operator: In
                    values:
                      - varlogmr
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
