---
kind: Service
apiVersion: v1
metadata:
  name: varlogmr-rpc-vip
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  ports:
    - name: varlogmr-rpc
      port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: varlogadm-rpc-vip
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  ports:
    - name: varlogadm-rpc
      port: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-ui-vip
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  ports:
    - name: prometheus-ui
      port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui-vip
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  ports:
    - name: jaeger-ui
      port: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-vip
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
spec:
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
  ports:
    - name: grafana
      port: 3000
