name: backport
on:
  push:
    branches:
      - release/*
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.2.0
        with:
          token: ${{ secrets.VARLOG_GITHUB_TOKEN }}
          release-type: go
