name: backport
on:
  push:
    branches:
      - release/*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.1.4
        with:
          token: ${{ secrets.VARLOG_GITHUB_TOKEN }}
          release-type: go
          target-branch: ${{ github.ref_name }}
